In [1]:
import pandas as pd

df = pd.read_csv("jan to may police violation_anonymized791b166.csv")
print(df.shape)
print(df.columns.tolist())
df.head()
df.info()

(298450, 24)
['id', 'latitude', 'longitude', 'location', 'vehicle_number', 'vehicle_type', 'description', 'violation_type', 'offence_code', 'created_datetime', 'closed_datetime', 'modified_datetime', 'device_id', 'created_by_id', 'center_code', 'police_station', 'data_sent_to_scita', 'junction_name', 'action_taken_timestamp', 'data_sent_to_scita_timestamp', 'updated_vehicle_number', 'updated_vehicle_type', 'validation_status', 'validation_timestamp']
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 298450 entries, 0 to 298449
Data columns (total 24 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   id                            298450 non-null  object
 1   latitude                      298450 non-null  float64
 2   longitude                     298450 non-null  float64
 3   location                      295409 non-null  object
 4   vehicle_number                298450 non-null  object
 5   vehicle_type                  298450 non-null  object
 6   description                   0 non-null       float64
 7   violation_type                298450 non-null  object
 8   offence_code                  298450 non-null  object
 9   created_datetime              298450 non-null  object
 10  closed_datetime               0 non-null       float64
 11  modified_datetime             298450 non-null  object
 12  device_id                     298450 non-null  object
 13  created_by_id                 298445 non-null  object
 14  center_code                   287190 non-null  float64
 15  police_station                298445 non-null  object
 16  data_sent_to_scita            298450 non-null  bool
 17  junction_name                 298445 non-null  object
 18  action_taken_timestamp        0 non-null       float64
 19  data_sent_to_scita_timestamp  42161 non-null   object
 20  updated_vehicle_number        173196 non-null  object
 21  updated_vehicle_type          173196 non-null  object
 22  validation_status             173196 non-null  object
 23  validation_timestamp          173196 non-null  object
dtypes: bool(1), float64(6), object(17)
memory usage: 52.7+ MB

In [2]:
print(df["vehicle_type"].value_counts().head(20))

vehicle_type
SCOOTER                94856
CAR                    88870
MOTOR CYCLE            40811
PASSENGER AUTO         37813
MAXI-CAB               11372
LGV                     8255
GOODS AUTO              2934
MOPED                   2199
PRIVATE BUS             1633
VAN                     1466
TEMPO                   1368
BUS (BMTC/KSRTC)        1281
HGV                     1144
LORRY/GOODS VEHICLE     1122
JEEP                     913
OTHERS                   895
TOURIST BUS              379
SCHOOL VEHICLE           378
TANKER                   260
FACTORY BUS              238
Name: count, dtype: int64

In [3]:
print(df["violation_type"].value_counts().head(20))

violation_type
["WRONG PARKING"]                                           138764
["NO PARKING"]                                              119576
["PARKING IN A MAIN ROAD","WRONG PARKING"]                    9472
["PARKING IN A MAIN ROAD","NO PARKING"]                       4818
["WRONG PARKING","DEFECTIVE NUMBER PLATE"]                    3317
["NO PARKING","PARKING IN A MAIN ROAD"]                       2449
["NO PARKING","DEFECTIVE NUMBER PLATE"]                       2380
["WRONG PARKING","PARKING IN A MAIN ROAD"]                    1955
["PARKING ON FOOTPATH","WRONG PARKING"]                       1190
["NO PARKING","WRONG PARKING"]                                 891
["PARKING IN A MAIN ROAD","WRONG PARKING","NO PARKING"]        865
["WRONG PARKING","NO PARKING"]                                 827
["PARKING ON FOOTPATH","NO PARKING"]                           682
["NO PARKING","WRONG PARKING","PARKING IN A MAIN ROAD"]        675
["WRONG PARKING","PARKING ON FOOTPATH"]                        466
["NO PARKING","PARKING NEAR BUSTOP/SCHOOL/HOSPITAL ETC"]       389
["DEFECTIVE NUMBER PLATE","WRONG PARKING"]                     380
["NO PARKING","DOUBLE PARKING"]                                367
["NO PARKING","PARKING ON FOOTPATH"]                           344
["WRONG PARKING","REFUSE TO GO FOR HIRE"]                      329
Name: count, dtype: int64

In [4]:
print(df["junction_name"].value_counts().head(20))

junction_name
No Junction                                   147880
BTP051 - Safina Plaza Junction                 15449
BTP082 - KR Market Junction                    11538
BTP040 - Elite Junction                        10718
BTP044 - Sagar Theatre Junction                10549
BTP211 - Central Street Junction                5388
BTP058 - Subbanna Junction                      5189
BTP027 - Modi Bridge Junction                   4584
BTP020 - Hosahalli Metro Station                4101
BTP057 - Anand Rao Junction                     3935
BTP080 - NR Road, SP Road Junction              3681
BTP045 - Danvanthri Road Junction               3181
BTP001 - 10th Cross, Dr. Rajkumar Road          2812
BTP083 - AS Char Street, Mysore Road            2778
BTP032 - Windsor Circle                         2749
BTP016 - 5th Main Road, RPC Layout              2474
BTP070 - Cholurpalya Junction, Magadi Road      2272
BTP042 - Minsk Square Junction (CTO)            2044
BTP038 - Mysore Bank Junction                   2021
BTP023 - Mahalaxmi Layout Entrance              1807
Name: count, dtype: int64

In [5]:
print(df["police_station"].value_counts().head(20))

police_station
Upparpet                  34468
Shivajinagar              28044
Malleshwaram              22200
HAL Old Airport           20819
City Market               17646
Vijayanagara              14652
Rajajinagar               10998
Kodigehalli               10916
Magadi Road                8558
Jeevanbheemanagar          6736
K.R. Pura                  6546
Halasuru Gate              6294
Mahadevapura               6187
Chikkajala                 5834
HSR Layout                 5018
Bellandur                  4964
High ground                4951
Byatarayanapura            4555
Electronic City            4333
Pulikeshinagar(F.Town)     4136
Name: count, dtype: int64

In [6]:
df["created_datetime"] = pd.to_datetime(df["created_datetime"])

df["hour"] = df["created_datetime"].dt.hour
df["weekday"] = df["created_datetime"].dt.day_name()
df["month"] = df["created_datetime"].dt.month_name()

print(df["hour"].value_counts().sort_index())
print(df["weekday"].value_counts())
print(df["month"].value_counts())

ValueError: time data "2024-03-20 03:30:21.022782+00" doesn't match format "%Y-%m-%d %H:%M:%S%z", at position 31001. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [7]:
df["created_datetime"] = pd.to_datetime(
    df["created_datetime"],
    format="mixed",
    utc=True
)

In [8]:
df["hour"] = df["created_datetime"].dt.hour
df["weekday"] = df["created_datetime"].dt.day_name()
df["month"] = df["created_datetime"].dt.month_name()

In [9]:
print(df["hour"].value_counts().sort_index())
print(df["weekday"].value_counts())
print(df["month"].value_counts())

hour
0     21762
1     17155
2     24770
3     25709
4     29102
5     34085
6     26890
7     14608
8      8556
9      3145
10      518
11      577
12      219
13       56
14       16
15       66
16      416
17      818
18     1971
19    10713
20    11834
21    19763
22    22840
23    22861
Name: count, dtype: int64
weekday
Sunday       46865
Saturday     43427
Wednesday    43067
Tuesday      42930
Friday       41702
Thursday     41528
Monday       38931
Name: count, dtype: int64
month
January     65813
December    63555
March       55231
February    54650
November    44119
April       15082
Name: count, dtype: int64

In [10]:
print(df["created_datetime"].min())
print(df["created_datetime"].max())

2023-11-09 19:11:46+00:00
2024-04-08 17:30:46+00:00

In [11]:
print(df["hour"].value_counts().sort_index())

hour
0     21762
1     17155
2     24770
3     25709
4     29102
5     34085
6     26890
7     14608
8      8556
9      3145
10      518
11      577
12      219
13       56
14       16
15       66
16      416
17      818
18     1971
19    10713
20    11834
21    19763
22    22840
23    22861
Name: count, dtype: int64

In [12]:
print(df["weekday"].value_counts())

weekday
Sunday       46865
Saturday     43427
Wednesday    43067
Tuesday      42930
Friday       41702
Thursday     41528
Monday       38931
Name: count, dtype: int64

In [13]:
print(df["month"].value_counts())

month
January     65813
December    63555
March       55231
February    54650
November    44119
April       15082
Name: count, dtype: int64

In [14]:
df["hour_ist"] = (
    df["created_datetime"]
    .dt.tz_convert("Asia/Kolkata")
    .dt.hour
)

print(df["hour_ist"].value_counts().sort_index())

hour_ist
0      5815
1     11098
2     16261
3     21565
4     23513
5     22193
6     19838
7     19445
8     25790
9     26996
10    32580
11    32176
12    19689
13    11546
14     5634
15     1224
16      583
17      377
18      150
19       27
20       42
21      148
22      725
23     1035
Name: count, dtype: int64

In [15]:
df["date"] = df["created_datetime"].dt.date

daily_junction = (
    df.groupby(["date", "junction_name"])
      .size()
      .reset_index(name="violations")
)

print(daily_junction.head())
print(daily_junction.shape)

         date                         junction_name  violations
0  2023-11-09             BTP008 - Navarang Theatre           9
1  2023-11-09    BTP016 - 5th Main Road, RPC Layout          19
2  2023-11-09               BTP040 - Elite Junction           1
3  2023-11-09  BTP042 - Minsk Square Junction (CTO)           2
4  2023-11-09       BTP044 - Sagar Theatre Junction           1
(11579, 3)

In [16]:
top_junctions = (
    df["junction_name"]
    .value_counts()
    .head(20)
)

print(top_junctions)

junction_name
No Junction                                   147880
BTP051 - Safina Plaza Junction                 15449
BTP082 - KR Market Junction                    11538
BTP040 - Elite Junction                        10718
BTP044 - Sagar Theatre Junction                10549
BTP211 - Central Street Junction                5388
BTP058 - Subbanna Junction                      5189
BTP027 - Modi Bridge Junction                   4584
BTP020 - Hosahalli Metro Station                4101
BTP057 - Anand Rao Junction                     3935
BTP080 - NR Road, SP Road Junction              3681
BTP045 - Danvanthri Road Junction               3181
BTP001 - 10th Cross, Dr. Rajkumar Road          2812
BTP083 - AS Char Street, Mysore Road            2778
BTP032 - Windsor Circle                         2749
BTP016 - 5th Main Road, RPC Layout              2474
BTP070 - Cholurpalya Junction, Magadi Road      2272
BTP042 - Minsk Square Junction (CTO)            2044
BTP038 - Mysore Bank Junction                   2021
BTP023 - Mahalaxmi Layout Entrance              1807
Name: count, dtype: int64

In [17]:
monthly_junction = (
    df.groupby(["month", "junction_name"])
      .size()
      .reset_index(name="violations")
)

print(monthly_junction.head())
print(monthly_junction.shape)

   month                           junction_name  violations
0  April  BTP001 - 10th Cross, Dr. Rajkumar Road         190
1  April          BTP006 - Navarang Bar Junction          13
2  April               BTP008 - Navarang Theatre          94
3  April         BTP009 - Prakash Nagar Junction          18
4  April           BTP010 - Rajajinagar Entrance          31
(973, 3)

In [18]:
top_junctions = (
    df[df["junction_name"] != "No Junction"]
    ["junction_name"]
    .value_counts()
    .head(10)
    .index
)

print(top_junctions)

Index(['BTP051 - Safina Plaza Junction', 'BTP082 - KR Market Junction',
       'BTP040 - Elite Junction', 'BTP044 - Sagar Theatre Junction',
       'BTP211 - Central Street Junction', 'BTP058 - Subbanna Junction',
       'BTP027 - Modi Bridge Junction', 'BTP020 - Hosahalli Metro Station',
       'BTP057 - Anand Rao Junction', 'BTP080 - NR Road, SP Road Junction'],
      dtype='object', name='junction_name')

In [19]:
for junction in top_junctions:
    print("\n", junction)
    print(
        monthly_junction[
            monthly_junction["junction_name"] == junction
        ][["month", "violations"]]
    )

 BTP051 - Safina Plaza Junction
        month  violations
32      April         690
185  December        2409
351  February        2489
513   January        3612
679     March        2980
844  November        3269

 BTP082 - KR Market Junction
        month  violations
52      April         533
207  December        2104
372  February        2394
535   January        2815
701     March        2648
866  November        1044

 BTP040 - Elite Junction
        month  violations
24      April         690
177  December        2467
343  February        1608
505   January        2188
671     March        2025
836  November        1740

 BTP044 - Sagar Theatre Junction
        month  violations
28      April         587
181  December        1990
347  February        1932
509   January        2530
675     March        1728
840  November        1782

 BTP211 - Central Street Junction
        month  violations
138     April         148
302  December         772
464  February         700
631   January        1799
795     March        1093
958  November         876

 BTP058 - Subbanna Junction
        month  violations
36      April         456
190  December        1222
355  February         676
518   January        1011
684     March         872
849  November         952

 BTP027 - Modi Bridge Junction
        month  violations
15      April         249
167  December        1150
333  February         818
495   January         847
661     March         666
826  November         854

 BTP020 - Hosahalli Metro Station
        month  violations
9       April          71
161  December        1258
327  February         656
489   January        1005
655     March         516
820  November         595

 BTP057 - Anand Rao Junction
        month  violations
35      April         243
189  December        1021
354  February         398
517   January         749
683     March         739
848  November         785

 BTP080 - NR Road, SP Road Junction
        month  violations
51      April         187
206  December         812
371  February         936
534   January         536
700     March         652
865  November         558

In [20]:
df["date"] = df["created_datetime"].dt.date

risk_data = (
    df.groupby(
        [
            "junction_name",
            "date",
            "hour_ist"
        ]
    )
    .size()
    .reset_index(name="violations")
)

print(risk_data.shape)
print(risk_data.head())

(34457, 4)
                            junction_name        date  hour_ist  violations
0  BTP001 - 10th Cross, Dr. Rajkumar Road  2023-11-10         3           1
1  BTP001 - 10th Cross, Dr. Rajkumar Road  2023-11-10         6           2
2  BTP001 - 10th Cross, Dr. Rajkumar Road  2023-11-10        11           2
3  BTP001 - 10th Cross, Dr. Rajkumar Road  2023-11-10        13           1
4  BTP001 - 10th Cross, Dr. Rajkumar Road  2023-11-11         2           2

In [21]:
print(risk_data["violations"].describe())

count    34457.000000
mean         8.661375
std         19.379774
min          1.000000
25%          1.000000
50%          2.000000
75%          7.000000
max        251.000000
Name: violations, dtype: float64

In [22]:
print(
    risk_data.sort_values(
        "violations",
        ascending=False
    ).head(20)
)

      junction_name        date  hour_ist  violations
32802   No Junction  2024-01-05         4         251
32905   No Junction  2024-01-11         4         240
31898   No Junction  2023-11-12        10         230
32346   No Junction  2023-12-09         6         228
32608   No Junction  2023-12-24        12         222
33337   No Junction  2024-02-05        10         222
32722   No Junction  2023-12-31        10         214
33101   No Junction  2024-01-22        11         206
33514   No Junction  2024-02-15         8         202
33286   No Junction  2024-02-02        11         198
33675   No Junction  2024-02-24        11         198
33031   No Junction  2024-01-18        11         196
32410   No Junction  2023-12-13         3         195
32787   No Junction  2024-01-04         6         193
32801   No Junction  2024-01-05         3         191
33015   No Junction  2024-01-17        11         191
32659   No Junction  2023-12-27        11         191
33976   No Junction  2024-03-12         8         191
32348   No Junction  2023-12-09         8         190
32843   No Junction  2024-01-07        10         189

In [23]:
model_df = df.copy()

model_df["date"] = model_df["created_datetime"].dt.date

risk_data = (
    model_df.groupby(
        [
            "junction_name",
            "police_station",
            "date",
            "hour_ist"
        ]
    )
    .size()
    .reset_index(name="violations")
)

risk_data["date"] = pd.to_datetime(risk_data["date"])

risk_data["day_of_week"] = risk_data["date"].dt.dayofweek
risk_data["month"] = risk_data["date"].dt.month
risk_data["day"] = risk_data["date"].dt.day

print(risk_data.shape)
risk_data.head()

(63354, 8)

,junction_name,police_station,date,hour_ist,violations,day_of_week,month,day
0,"BTP001 - 10th Cross, Dr. Rajkumar Road",Malleshwaram,2023-11-10,3,1,4,11,10
1,"BTP001 - 10th Cross, Dr. Rajkumar Road",Malleshwaram,2023-11-10,6,2,4,11,10
2,"BTP001 - 10th Cross, Dr. Rajkumar Road",Malleshwaram,2023-11-10,11,2,4,11,10
3,"BTP001 - 10th Cross, Dr. Rajkumar Road",Malleshwaram,2023-11-10,13,1,4,11,10
4,"BTP001 - 10th Cross, Dr. Rajkumar Road",Malleshwaram,2023-11-11,2,2,5,11,11

In [24]:
# Junction average violations
risk_data["junction_avg"] = risk_data.groupby(
    "junction_name"
)["violations"].transform("mean")

# Police station average violations
risk_data["station_avg"] = risk_data.groupby(
    "police_station"
)["violations"].transform("mean")

# Hour average violations
risk_data["hour_avg"] = risk_data.groupby(
    "hour_ist"
)["violations"].transform("mean")

# Day-of-week average violations
risk_data["dow_avg"] = risk_data.groupby(
    "day_of_week"
)["violations"].transform("mean")

print(risk_data.head())

                            junction_name police_station       date  hour_ist  \
0  BTP001 - 10th Cross, Dr. Rajkumar Road   Malleshwaram 2023-11-10         3
1  BTP001 - 10th Cross, Dr. Rajkumar Road   Malleshwaram 2023-11-10         6
2  BTP001 - 10th Cross, Dr. Rajkumar Road   Malleshwaram 2023-11-10        11
3  BTP001 - 10th Cross, Dr. Rajkumar Road   Malleshwaram 2023-11-10        13
4  BTP001 - 10th Cross, Dr. Rajkumar Road   Malleshwaram 2023-11-11         2

   violations  day_of_week  month  day  junction_avg  station_avg  hour_avg  \
0           1            4     11   10      4.839931     6.826568  4.326846
1           2            4     11   10      4.839931     6.826568  4.542249
2           2            4     11   10      4.839931     6.826568  5.031431
3           1            4     11   10      4.839931     6.826568  3.819385
4           2            5     11   11      4.839931     6.826568  3.907955

    dow_avg
0  4.539734
1  4.539734
2  4.539734
3  4.539734
4  4.525531

In [25]:
risk_data[
    [
        "junction_name",
        "violations",
        "junction_avg",
        "station_avg",
        "hour_avg",
        "dow_avg"
    ]
].head()

,junction_name,violations,junction_avg,station_avg,hour_avg,dow_avg
0,"BTP001 - 10th Cross, Dr. Rajkumar Road",1,4.839931,6.826568,4.326846,4.539734
1,"BTP001 - 10th Cross, Dr. Rajkumar Road",2,4.839931,6.826568,4.542249,4.539734
2,"BTP001 - 10th Cross, Dr. Rajkumar Road",2,4.839931,6.826568,5.031431,4.539734
3,"BTP001 - 10th Cross, Dr. Rajkumar Road",1,4.839931,6.826568,3.819385,4.539734
4,"BTP001 - 10th Cross, Dr. Rajkumar Road",2,4.839931,6.826568,3.907955,4.525531

In [26]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
from catboost import CatBoostRegressor

X = risk_data[
    [
        "junction_name",
        "police_station",
        "hour_ist",
        "day_of_week",
        "month",
        "day",
        "junction_avg",
        "station_avg",
        "hour_avg",
        "dow_avg"
    ]
]

y = risk_data["violations"]

X_train, X_valid, y_train, y_valid = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

cat_features = [
    "junction_name",
    "police_station"
]

model = CatBoostRegressor(
    iterations=1000,
    learning_rate=0.05,
    depth=6,
    loss_function="RMSE",
    eval_metric="R2",
    random_seed=42,
    verbose=100
)

model.fit(
    X_train,
    y_train,
    cat_features=cat_features,
    eval_set=(X_valid, y_valid)
)

preds = model.predict(X_valid)

print("R2 Score:", r2_score(y_valid, preds))

0:	learn: 0.0115865	test: 0.0120735	best: 0.0120735 (0)	total: 207ms	remaining: 3m 26s
100:	learn: 0.1965085	test: 0.1914674	best: 0.1914674 (100)	total: 5.68s	remaining: 50.5s
200:	learn: 0.2230480	test: 0.2064408	best: 0.2064408 (200)	total: 11.2s	remaining: 44.4s
300:	learn: 0.2410979	test: 0.2150907	best: 0.2151310 (298)	total: 16.4s	remaining: 38s
400:	learn: 0.2533597	test: 0.2186145	best: 0.2186145 (400)	total: 22.8s	remaining: 34s
500:	learn: 0.2644118	test: 0.2209359	best: 0.2209359 (500)	total: 28.9s	remaining: 28.8s
600:	learn: 0.2726843	test: 0.2220279	best: 0.2221379 (592)	total: 34s	remaining: 22.6s
700:	learn: 0.2811641	test: 0.2232288	best: 0.2232420 (699)	total: 43s	remaining: 18.3s
800:	learn: 0.2894627	test: 0.2244223	best: 0.2244616 (790)	total: 49.3s	remaining: 12.3s
900:	learn: 0.2964425	test: 0.2252902	best: 0.2252902 (900)	total: 54.1s	remaining: 5.95s
999:	learn: 0.3025940	test: 0.2272527	best: 0.2273063 (995)	total: 59.3s	remaining: 0us

bestTest = 0.2273063486
bestIteration = 995

Shrink model to first 996 iterations.
R2 Score: 0.22730634861995702

In [27]:
top_hotspots = (
    df.groupby(
        [
            "junction_name",
            "police_station"
        ]
    )
    .size()
    .reset_index(name="violations")
    .sort_values(
        "violations",
        ascending=False
    )
)

print(top_hotspots.head(20))

                        junction_name          police_station  violations
317                       No Junction         HAL Old Airport       20819
66     BTP051 - Safina Plaza Junction            Shivajinagar       15298
339                       No Junction            Malleshwaram       14756
335                       No Junction             Kodigehalli       10916
51            BTP040 - Elite Junction                Upparpet       10718
105       BTP082 - KR Market Junction             City Market       10109
59    BTP044 - Sagar Theatre Junction                Upparpet       10049
331                       No Junction               K.R. Pura        6546
338                       No Junction            Mahadevapura        6187
328                       No Junction       Jeevanbheemanagar        5981
312                       No Junction              Chikkajala        5834
282  BTP211 - Central Street Junction            Shivajinagar        5373
348                       No Junction            Shivajinagar        5248
318                       No Junction              HSR Layout        5018
308                       No Junction               Bellandur        4964
80         BTP058 - Subbanna Junction                Upparpet        4830
316                       No Junction         Electronic City        4333
343                       No Junction  Pulikeshinagar(F.Town)        4136
18   BTP020 - Hosahalli Metro Station            Vijayanagara        4035
306                       No Junction               Banaswadi        3759

In [28]:
station_summary = (
    df.groupby("police_station")
    .size()
    .reset_index(name="violations")
    .sort_values(
        "violations",
        ascending=False
    )
)

print(station_summary.head(20))

            police_station  violations
47                Upparpet       34468
45            Shivajinagar       28044
36            Malleshwaram       22200
14         HAL Old Airport       20819
10             City Market       17646
49            Vijayanagara       14652
42             Rajajinagar       10998
32             Kodigehalli       10916
34             Magadi Road        8558
25       Jeevanbheemanagar        6736
28               K.R. Pura        6546
17           Halasuru Gate        6294
35            Mahadevapura        6187
9               Chikkajala        5834
15              HSR Layout        5018
5                Bellandur        4964
20             High ground        4951
6          Byatarayanapura        4555
13         Electronic City        4333
40  Pulikeshinagar(F.Town)        4136

In [29]:
# Peak hour flag

risk_data["is_peak_hour"] = risk_data["hour_ist"].apply(
    lambda x: 1 if x in [8,9,10,11] else 0
)

# Junction frequency

junction_freq = (
    risk_data.groupby("junction_name")["violations"]
    .sum()
)

risk_data["junction_total"] = risk_data["junction_name"].map(
    junction_freq
)

# Hour intensity

hour_freq = (
    risk_data.groupby("hour_ist")["violations"]
    .sum()
)

risk_data["hour_total"] = risk_data["hour_ist"].map(
    hour_freq
)

print(
    risk_data[
        [
            "junction_name",
            "violations",
            "junction_total",
            "hour_total",
            "is_peak_hour"
        ]
    ].head()
)

                            junction_name  violations  junction_total  \
0  BTP001 - 10th Cross, Dr. Rajkumar Road           1            2812
1  BTP001 - 10th Cross, Dr. Rajkumar Road           2            2812
2  BTP001 - 10th Cross, Dr. Rajkumar Road           2            2812
3  BTP001 - 10th Cross, Dr. Rajkumar Road           1            2812
4  BTP001 - 10th Cross, Dr. Rajkumar Road           2            2812

   hour_total  is_peak_hour
0       21565             0
1       19836             0
2       32176             1
3       11546             0
4       16261             0

In [30]:
junction_stats = (
    risk_data.groupby("junction_name")
    .agg({
        "violations": ["sum", "mean", "max"],
        "is_peak_hour": "sum"
    })
)

junction_stats.columns = [
    "total_violations",
    "avg_violations",
    "max_violations",
    "peak_occurrences"
]

junction_stats = junction_stats.reset_index()

junction_stats.head()

,junction_name,total_violations,avg_violations,max_violations,peak_occurrences
0,"BTP001 - 10th Cross, Dr. Rajkumar Road",2812,4.839931,41,188
1,BTP006 - Navarang Bar Junction,47,2.937500,7,3
2,BTP008 - Navarang Theatre,1190,3.148148,22,170
3,BTP009 - Prakash Nagar Junction,262,5.346939,22,9
4,BTP010 - Rajajinagar Entrance,957,2.380597,30,154

In [31]:
print(junction_stats.shape)

print(
    junction_stats.sort_values(
        "total_violations",
        ascending=False
    ).head(10)
)

(169, 5)
                        junction_name  total_violations  avg_violations  \
168                       No Junction            147880        5.062476
34     BTP051 - Safina Plaza Junction             15449       11.058697
56        BTP082 - KR Market Junction             11538        6.133971
26            BTP040 - Elite Junction             10718        8.257319
30    BTP044 - Sagar Theatre Junction             10549        6.714831
154  BTP211 - Central Street Junction              5388        5.600832
39         BTP058 - Subbanna Junction              5189        6.551768
16      BTP027 - Modi Bridge Junction              4584        4.971800
10   BTP020 - Hosahalli Metro Station              4101       10.150990
38        BTP057 - Anand Rao Junction              3935        3.736942

     max_violations  peak_occurrences
168             153              9292
34              133               577
56              102               605
26               93               450
30               81               575
154              50               360
39               61               263
16              123               374
10              106               156
38               31               310

In [32]:
from sklearn.preprocessing import MinMaxScaler

junction_stats_model = junction_stats.copy()

scaler = MinMaxScaler()

junction_stats_model[
    [
        "total_norm",
        "avg_norm",
        "max_norm",
        "peak_norm"
    ]
] = scaler.fit_transform(
    junction_stats_model[
        [
            "total_violations",
            "avg_violations",
            "max_violations",
            "peak_occurrences"
        ]
    ]
)

junction_stats_model["PIS"] = (
    0.35 * junction_stats_model["total_norm"] +
    0.25 * junction_stats_model["avg_norm"] +
    0.20 * junction_stats_model["max_norm"] +
    0.20 * junction_stats_model["peak_norm"]
)

junction_stats_model = junction_stats_model.sort_values(
    "PIS",
    ascending=False
)

print(
    junction_stats_model[
        [
            "junction_name",
            "PIS",
            "total_violations",
            "avg_violations",
            "max_violations"
        ]
    ].head(20)
)

                                      junction_name       PIS  \
168                                     No Junction  0.849094
34                   BTP051 - Safina Plaza Junction  0.472481
10                 BTP020 - Hosahalli Metro Station  0.377954
26                          BTP040 - Elite Junction  0.335068
56                      BTP082 - KR Market Junction  0.298827
28             BTP042 - Minsk Square Junction (CTO)  0.293003
30                  BTP044 - Sagar Theatre Junction  0.282645
16                    BTP027 - Modi Bridge Junction  0.275962
19                          BTP032 - Windsor Circle  0.266267
47       BTP070 - Cholurpalya Junction, Magadi Road  0.265215
8                         BTP017 - Attiguppe Circle  0.237442
39                       BTP058 - Subbanna Junction  0.232649
7                BTP016 - 5th Main Road, RPC Layout  0.216459
55               BTP080 - NR Road, SP Road Junction  0.197251
154                BTP211 - Central Street Junction  0.196706
123                        BTP172 - Nanjappa Circle  0.187405
136        BTP188 - 27th Cross, 4th Main, Jayanagar  0.187317
5    BTP011 - RR Kalyana Mantapa, Dr. Rajkumar Road  0.181157
68                         BTP100 - Richmond Circle  0.180078
134         BTP186 - 9th Cross, 4th Main, Jayanagar  0.168017

     total_violations  avg_violations  max_violations
168            147880        5.062476             153
34              15449       11.058697             133
10               4101       10.150990             106
26              10718        8.257319              93
56              11538        6.133971             102
28               2044        7.432727              98
30              10549        6.714831              81
16               4584        4.971800             123
19               2749        6.721271              89
47               2272        8.573585              55
8                 422        8.612245              38
39               5189        6.551768              61
7                2474        7.341246              41
55               3681        5.014986              65
154              5388        5.600832              50
123               776        6.466667              40
136               294        6.681818              37
5                1208        5.807692              47
68                304        5.241379              59
134               546        5.352941              47

In [33]:
print(df["vehicle_type"].value_counts())

vehicle_type
SCOOTER                94856
CAR                    88870
MOTOR CYCLE            40811
PASSENGER AUTO         37813
MAXI-CAB               11372
LGV                     8255
GOODS AUTO              2934
MOPED                   2199
PRIVATE BUS             1633
VAN                     1466
TEMPO                   1368
BUS (BMTC/KSRTC)        1281
HGV                     1144
LORRY/GOODS VEHICLE     1122
JEEP                     913
OTHERS                   895
TOURIST BUS              379
SCHOOL VEHICLE           378
TANKER                   260
FACTORY BUS              238
MINI LORRY               199
TRACTOR                   64
Name: count, dtype: int64

In [34]:
print(
    df["violation_type"]
    .value_counts()
    .head(30)
)

violation_type
["WRONG PARKING"]                                                      138764
["NO PARKING"]                                                         119576
["PARKING IN A MAIN ROAD","WRONG PARKING"]                               9472
["PARKING IN A MAIN ROAD","NO PARKING"]                                  4818
["WRONG PARKING","DEFECTIVE NUMBER PLATE"]                               3317
["NO PARKING","PARKING IN A MAIN ROAD"]                                  2449
["NO PARKING","DEFECTIVE NUMBER PLATE"]                                  2380
["WRONG PARKING","PARKING IN A MAIN ROAD"]                               1955
["PARKING ON FOOTPATH","WRONG PARKING"]                                  1190
["NO PARKING","WRONG PARKING"]                                            891
["PARKING IN A MAIN ROAD","WRONG PARKING","NO PARKING"]                   865
["WRONG PARKING","NO PARKING"]                                            827
["PARKING ON FOOTPATH","NO PARKING"]                                      682
["NO PARKING","WRONG PARKING","PARKING IN A MAIN ROAD"]                   675
["WRONG PARKING","PARKING ON FOOTPATH"]                                   466
["NO PARKING","PARKING NEAR BUSTOP/SCHOOL/HOSPITAL ETC"]                  389
["DEFECTIVE NUMBER PLATE","WRONG PARKING"]                                380
["NO PARKING","DOUBLE PARKING"]                                           367
["NO PARKING","PARKING ON FOOTPATH"]                                      344
["WRONG PARKING","REFUSE TO GO FOR HIRE"]                                 329
["PARKING NEAR ROAD CROSSING","WRONG PARKING"]                            310
["DEFECTIVE NUMBER PLATE","NO PARKING"]                                   293
["WRONG PARKING","NO PARKING","PARKING IN A MAIN ROAD"]                   272
["PARKING IN A MAIN ROAD","WRONG PARKING","DEFECTIVE NUMBER PLATE"]       261
["WRONG PARKING","PARKING NEAR BUSTOP/SCHOOL/HOSPITAL ETC"]               239
["PARKING NEAR BUSTOP/SCHOOL/HOSPITAL ETC","WRONG PARKING"]               238
["WRONG PARKING","DOUBLE PARKING"]                                        237
["PARKING NEAR BUSTOP/SCHOOL/HOSPITAL ETC","NO PARKING"]                  182
["PARKING OTHER THAN BUS STOP","WRONG PARKING"]                           181
["PARKING ON FOOTPATH","WRONG PARKING","NO PARKING"]                      177
Name: count, dtype: int64

In [35]:
junction_features = junction_stats_model[
    [
        "total_violations",
        "avg_violations",
        "max_violations",
        "peak_occurrences"
    ]
].copy()

print(junction_features.shape)
junction_features.head()

(169, 4)

     total_violations  avg_violations  max_violations  peak_occurrences
168            147880        5.062476             153              9292
34              15449       11.058697             133               577
10               4101       10.150990             106               156
26              10718        8.257319              93               450
56              11538        6.133971             102               605

In [36]:
risk_data = risk_data.sort_values(
    ["junction_name", "date", "hour_ist"]
)

risk_data["lag_1"] = (
    risk_data.groupby("junction_name")["violations"]
    .shift(1)
)

risk_data["lag_7"] = (
    risk_data.groupby("junction_name")["violations"]
    .shift(7)
)

risk_data["rolling_mean_7"] = (
    risk_data.groupby("junction_name")["violations"]
    .transform(lambda x: x.shift(1).rolling(7).mean())
)

risk_data["rolling_max_7"] = (
    risk_data.groupby("junction_name")["violations"]
    .transform(lambda x: x.shift(1).rolling(7).max())
)

risk_data = risk_data.fillna(0)

print(
    risk_data[
        [
            "violations",
            "lag_1",
            "lag_7",
            "rolling_mean_7",
            "rolling_max_7"
        ]
    ].head(15)
)

    violations  lag_1  lag_7  rolling_mean_7  rolling_max_7
0            1    0.0    0.0        0.000000            0.0
1            2    1.0    0.0        0.000000            0.0
2            2    2.0    0.0        0.000000            0.0
3            1    2.0    0.0        0.000000            0.0
4            2    1.0    0.0        0.000000            0.0
5            6    2.0    0.0        0.000000            0.0
6            1    6.0    0.0        0.000000            0.0
7            5    1.0    1.0        2.142857            6.0
8            3    5.0    2.0        2.714286            6.0
9            4    3.0    2.0        2.857143            6.0
10           7    4.0    1.0        3.142857            6.0
11           1    7.0    2.0        4.000000            7.0
12          10    1.0    6.0        3.857143            7.0
13          15   10.0    1.0        4.428571           10.0
14           2   15.0    5.0        6.428571           15.0

In [37]:
features = [
    "junction_name",
    "police_station",
    "hour_ist",
    "day_of_week",
    "month",
    "day",
    "junction_avg",
    "station_avg",
    "hour_avg",
    "dow_avg",
    "lag_1",
    "lag_7",
    "rolling_mean_7",
    "rolling_max_7"
]

X = risk_data[features]
y = risk_data["violations"]

X_train, X_valid, y_train, y_valid = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

cat_features = [
    "junction_name",
    "police_station"
]

model = CatBoostRegressor(
    iterations=3000,
    learning_rate=0.03,
    depth=8,
    loss_function="RMSE",
    eval_metric="R2",
    random_seed=42,
    early_stopping_rounds=200,
    verbose=100
)

model.fit(
    X_train,
    y_train,
    cat_features=cat_features,
    eval_set=(X_valid, y_valid)
)

preds = model.predict(X_valid)

print("R2 Score:", r2_score(y_valid, preds))

0:	learn: 0.0085442	test: 0.0080912	best: 0.0080912 (0)	total: 132ms	remaining: 6m 34s
100:	learn: 0.2145549	test: 0.1913708	best: 0.1913708 (100)	total: 8.01s	remaining: 3m 49s
200:	learn: 0.2433407	test: 0.2047928	best: 0.2047928 (200)	total: 15.2s	remaining: 3m 31s
300:	learn: 0.2611940	test: 0.2106575	best: 0.2106575 (300)	total: 22.3s	remaining: 3m 19s
400:	learn: 0.2759449	test: 0.2153556	best: 0.2153566 (398)	total: 29.4s	remaining: 3m 10s
500:	learn: 0.2885271	test: 0.2184862	best: 0.2184862 (500)	total: 37s	remaining: 3m 4s
600:	learn: 0.3013155	test: 0.2199118	best: 0.2199591 (577)	total: 44.4s	remaining: 2m 57s
700:	learn: 0.3146795	test: 0.2214015	best: 0.2214015 (700)	total: 51.8s	remaining: 2m 49s
800:	learn: 0.3265831	test: 0.2234026	best: 0.2234026 (800)	total: 59.4s	remaining: 2m 43s
900:	learn: 0.3391131	test: 0.2250813	best: 0.2251101 (881)	total: 1m 6s	remaining: 2m 35s
1000:	learn: 0.3503267	test: 0.2263516	best: 0.2263516 (1000)	total: 1m 14s	remaining: 2m 28s
1100:	learn: 0.3597852	test: 0.2268186	best: 0.2268204 (1099)	total: 1m 21s	remaining: 2m 20s
1200:	learn: 0.3695780	test: 0.2279515	best: 0.2279515 (1200)	total: 1m 29s	remaining: 2m 13s
1300:	learn: 0.3786640	test: 0.2284061	best: 0.2284441 (1299)	total: 1m 36s	remaining: 2m 6s
1400:	learn: 0.3879542	test: 0.2291438	best: 0.2291537 (1398)	total: 1m 44s	remaining: 1m 59s
1500:	learn: 0.3961745	test: 0.2295800	best: 0.2295805 (1497)	total: 1m 52s	remaining: 1m 52s
1600:	learn: 0.4030426	test: 0.2297242	best: 0.2297579 (1573)	total: 2m	remaining: 1m 44s
1700:	learn: 0.4094507	test: 0.2299500	best: 0.2299500 (1700)	total: 2m 7s	remaining: 1m 37s
1800:	learn: 0.4169458	test: 0.2300380	best: 0.2301942 (1744)	total: 2m 15s	remaining: 1m 30s
1900:	learn: 0.4242545	test: 0.2297765	best: 0.2301990 (1829)	total: 2m 22s	remaining: 1m 22s
2000:	learn: 0.4311963	test: 0.2302202	best: 0.2302202 (2000)	total: 2m 30s	remaining: 1m 14s
2100:	learn: 0.4375269	test: 0.2304315	best: 0.2304347 (2071)	total: 2m 37s	remaining: 1m 7s
2200:	learn: 0.4449414	test: 0.2306819	best: 0.2307035 (2198)	total: 2m 44s	remaining: 59.9s
2300:	learn: 0.4516711	test: 0.2304900	best: 0.2308374 (2211)	total: 2m 52s	remaining: 52.3s
2400:	learn: 0.4578337	test: 0.2301935	best: 0.2308374 (2211)	total: 2m 59s	remaining: 44.8s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.2308374209
bestIteration = 2211

Shrink model to first 2212 iterations.
R2 Score: 0.23083742089652992

In [38]:
from sklearn.preprocessing import StandardScaler

cluster_df = junction_stats_model[
    [
        "total_violations",
        "avg_violations",
        "max_violations",
        "peak_occurrences"
    ]
].copy()

scaler = StandardScaler()

cluster_scaled = scaler.fit_transform(cluster_df)

print(cluster_scaled.shape)

(169, 4)

In [39]:
top10 = junction_stats_model[
    junction_stats_model["junction_name"] != "No Junction"
].head(10)["junction_name"]

behavior_df = risk_data[
    risk_data["junction_name"].isin(top10)
]

hour_pattern = (
    behavior_df.groupby(
        ["junction_name", "hour_ist"]
    )["violations"]
    .mean()
    .reset_index()
)

hour_pattern.head()

               junction_name  hour_ist  violations
0  BTP017 - Attiguppe Circle         1    3.000000
1  BTP017 - Attiguppe Circle         2    2.500000
2  BTP017 - Attiguppe Circle         3    5.400000
3  BTP017 - Attiguppe Circle         4    7.833333
4  BTP017 - Attiguppe Circle         5   10.400000

In [40]:
print(hour_pattern.shape)
hour_pattern.head(20)

(174, 3)

                       junction_name  hour_ist  violations
0          BTP017 - Attiguppe Circle         1    3.000000
1          BTP017 - Attiguppe Circle         2    2.500000
2          BTP017 - Attiguppe Circle         3    5.400000
3          BTP017 - Attiguppe Circle         4    7.833333
4          BTP017 - Attiguppe Circle         5   10.400000
5          BTP017 - Attiguppe Circle         6    8.000000
6          BTP017 - Attiguppe Circle         7    6.000000
7          BTP017 - Attiguppe Circle         8   10.000000
8          BTP017 - Attiguppe Circle         9   18.000000
9          BTP017 - Attiguppe Circle        10    7.600000
10         BTP017 - Attiguppe Circle        11   11.888889
11         BTP017 - Attiguppe Circle        12   12.142857
12         BTP017 - Attiguppe Circle        13    3.000000
13         BTP017 - Attiguppe Circle        14    1.000000
14  BTP020 - Hosahalli Metro Station         0    8.333333
15  BTP020 - Hosahalli Metro Station         1    3.500000
16  BTP020 - Hosahalli Metro Station         2    5.541667
17  BTP020 - Hosahalli Metro Station         3   12.605263
18  BTP020 - Hosahalli Metro Station         4   15.652174
19  BTP020 - Hosahalli Metro Station         5   10.279070

In [42]:
import pandas as pd
import numpy as np
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
import warnings
warnings.filterwarnings('ignore')

df = pd.read_csv("jan to may police violation_anonymized791b166.csv")
df['created_datetime'] = pd.to_datetime(df['created_datetime'], format='ISO8601', utc=True)
df['date']        = df['created_datetime'].dt.date
df['hour']        = df['created_datetime'].dt.hour
df['week']        = df['created_datetime'].dt.isocalendar().week.astype(int)
df['is_peak']     = df['hour'].apply(lambda x: 1 if (7<=x<=10 or 17<=x<=21) else 0)
df['junction_clean'] = df['junction_name'].str.strip()
df['is_heavy']    = df['vehicle_type'].isin([
    'HGV','LORRY/GOODS VEHICLE','TANKER','BUS (BMTC/KSRTC)',
    'PRIVATE BUS','TOURIST BUS','SCHOOL VEHICLE'
]).astype(int)

daily = df.groupby(['junction_clean','date']).size().reset_index(name='daily_count')
daily['date'] = pd.to_datetime(daily['date'])
daily['week'] = daily['date'].dt.isocalendar().week.astype(int)

junction_features = daily.groupby('junction_clean').agg(
    daily_avg   = ('daily_count', 'mean'),
    daily_std   = ('daily_count', 'std'),
    daily_max   = ('daily_count', 'max'),
    daily_min   = ('daily_count', 'min'),
    total_days  = ('daily_count', 'count')
).fillna(0)

weekly = daily.groupby(['junction_clean','week'])['daily_count'].sum().reset_index()
first_4 = weekly.groupby('junction_clean').apply(
    lambda x: x.nsmallest(4,'week')['daily_count'].mean()
).rename('first_4w_avg')
last_4 = weekly.groupby('junction_clean').apply(
    lambda x: x.nlargest(4,'week')['daily_count'].mean()
).rename('last_4w_avg')

junction_features = junction_features.join(first_4).join(last_4)
junction_features['wow_growth'] = (
    (junction_features['last_4w_avg'] - junction_features['first_4w_avg']) /
    junction_features['first_4w_avg'].clip(lower=1)
)

junction_features['spike_ratio'] = (
    junction_features['daily_max'] / junction_features['daily_avg'].clip(lower=1)
)

junction_features['consistency'] = 1 - (
    junction_features['daily_std'] / junction_features['daily_avg'].clip(lower=1)
).clip(0, 1)

print("Features built:", junction_features.shape)
print(junction_features.describe().round(2))

features_for_cluster = ['daily_avg','consistency','wow_growth','spike_ratio']
X = junction_features[features_for_cluster].fillna(0)
X_scaled = StandardScaler().fit_transform(X)

kmeans = KMeans(n_clusters=4, random_state=42, n_init=20)
junction_features['cluster'] = kmeans.fit_predict(X_scaled)

cluster_profiles = junction_features.groupby('cluster')[features_for_cluster].mean()
print("\nCluster profiles:")
print(cluster_profiles.round(3))

labels = {}
for c in range(4):
    profile = cluster_profiles.loc[c]
    if profile['daily_avg'] > cluster_profiles['daily_avg'].median() and profile['consistency'] > 0.5:
        labels[c] = 'PERSISTENT'
    elif profile['spike_ratio'] > cluster_profiles['spike_ratio'].median() and profile['consistency'] < 0.4:
        labels[c] = 'BURST'
    elif profile['wow_growth'] > 0.1:
        labels[c] = 'EMERGING'
    else:
        labels[c] = 'STABLE'

junction_features['hotspot_type'] = junction_features['cluster'].map(labels)
print("\nHotspot types assigned:")
print(junction_features['hotspot_type'].value_counts())

print("\nTop junctions per type:")
for htype in ['PERSISTENT','BURST','EMERGING','STABLE']:
    subset = junction_features[junction_features['hotspot_type']==htype]
    if len(subset) > 0:
        top = subset.sort_values('daily_avg', ascending=False).head(3)
        print(f"\n{htype}:")
        print(top[['daily_avg','consistency','wow_growth','spike_ratio']].round(2).to_string())

junction_features.to_csv('junction_behavior.csv')
print("\njunction_behavior.csv saved")

Features built: (169, 10)
       daily_avg  daily_std  daily_max  daily_min  total_days  first_4w_avg  \
count     169.00     169.00     169.00     169.00      169.00        169.00
mean       14.15       9.50      52.30       1.44       68.51         89.63
std        75.32      18.60     118.71       5.09       43.51        597.25
min         1.14       0.38       2.00       1.00        3.00          1.25
25%         3.14       3.02      14.00       1.00       33.00          4.00
50%         4.26       5.32      26.00       1.00       59.00         10.75
75%         8.40      10.19      52.00       1.00      105.00         32.25
max       972.89     213.08    1401.00      67.00      152.00       7671.00

       last_4w_avg  wow_growth  spike_ratio  consistency
count       169.00      169.00       169.00       169.00
mean         85.76        0.59         5.41         0.10
std         547.55        1.61         2.41         0.15
min           1.50       -0.88         1.44         0.00
25%           5.00       -0.25         3.86         0.00
50%          14.00        0.15         4.84         0.00
75%          39.50        0.75         7.00         0.16
max        7066.00        9.78        12.52         0.78

Cluster profiles:
         daily_avg  consistency  wow_growth  spike_ratio
cluster
0            7.265        0.015       0.268        6.186
1          972.895        0.781      -0.079        1.440
2           11.934        0.292       0.242        3.068
3            5.129        0.000       5.927        8.278

Hotspot types assigned:
hotspot_type
BURST         121
EMERGING       47
PERSISTENT      1
Name: count, dtype: int64

Top junctions per type:

PERSISTENT:
                daily_avg  consistency  wow_growth  spike_ratio
junction_clean
No Junction        972.89         0.78       -0.08         1.44

BURST:
                                  daily_avg  consistency  wow_growth  spike_ratio
junction_clean
BTP211 - Central Street Junction      36.16         0.00       -0.60         6.86
BTP020 - Hosahalli Metro Station      33.61         0.00        0.63         6.22
BTP027 - Modi Bridge Junction         31.40         0.11        0.39         5.35

EMERGING:
                                daily_avg  consistency  wow_growth  spike_ratio
junction_clean
BTP051 - Safina Plaza Junction     102.31         0.18       -0.37         4.27
BTP082 - KR Market Junction         75.91         0.39       -0.27         3.86
BTP040 - Elite Junction             70.51         0.40        0.08         3.16

junction_behavior.csv saved

In [1]:
list(globals().keys())[:50]

['__name__',
 '__doc__',
 '__package__',
 '__loader__',
 '__spec__',
 '__builtin__',
 '__builtins__',
 '_ih',
 '_oh',
 '_dh',
 'In',
 'Out',
 'get_ipython',
 'exit',
 'quit',
 'open',
 '_',
 '__',
 '___',
 '__vsc_ipynb_file__',
 '_i',
 '_ii',
 '_iii',
 '_i1']

In [3]:
import pandas as pd
import numpy as np

# Load dataset
df = pd.read_csv("jan to may police violation_anonymized791b166.csv")

# Parse datetime
df["created_datetime"] = pd.to_datetime(
    df["created_datetime"],
    format="ISO8601",
    utc=True
)

# Convert to IST
df["created_ist"] = (
    df["created_datetime"]
    .dt.tz_convert("Asia/Kolkata")
)

# Time features
df["date"] = df["created_ist"].dt.date
df["hour_ist"] = df["created_ist"].dt.hour
df["day_of_week"] = df["created_ist"].dt.dayofweek
df["month"] = df["created_ist"].dt.month

print(df.shape)
df.head()

(298450, 29)

,id,latitude,longitude,location,vehicle_number,vehicle_type,description,violation_type,offence_code,created_datetime,...,data_sent_to_scita_timestamp,updated_vehicle_number,updated_vehicle_type,validation_status,validation_timestamp,created_ist,date,hour_ist,day_of_week,month
0,FKID000000,12.925557,77.618665,"18th Main Road, Block 2, Koramangala, Bengalur...",FKN00GL0000,CAR,NaN,"[""WRONG PARKING"",""PARKING NEAR ROAD CROSSING""]","[112,104]",2023-11-20 00:28:46+00:00,...,NaN,FKN00GL0000,MAXI-CAB,approved,2023-11-30 03:08:24.818+00,2023-11-20 05:58:46+05:30,2023-11-20,5,0,11
1,FKID000001,12.905463,77.700778,"Sarjapura Main Road, The Grove, Janatha Colony...",FKN00GL0001,CAR,NaN,"[""NO PARKING""]",[113],2023-11-24 22:46:46+00:00,...,NaN,NaN,NaN,NaN,NaN,2023-11-25 04:16:46+05:30,2023-11-25,4,5,11
2,FKID000002,12.925449,77.618504,"Koramangala 2nd Block, Kormangala West, Bengal...",FKN00GL0002,CAR,NaN,"[""WRONG PARKING"",""PARKING IN A MAIN ROAD""]","[112,107]",2023-11-20 00:27:46+00:00,...,NaN,FKN00GL0002,MAXI-CAB,approved,2023-11-30 03:08:56.998+00,2023-11-20 05:57:46+05:30,2023-11-20,5,0,11
3,FKID000003,12.956521,77.518618,"6th Cross Road, Manasa Layout, Nagarbhavi, Ben...",FKN00GL0003,SCOOTER,NaN,"[""NO PARKING""]",[113],2023-11-16 06:47:46+00:00,...,NaN,FKN00GL0003,SCOOTER,approved,2023-11-18 23:35:12.428+00,2023-11-16 12:17:46+05:30,2023-11-16,12,3,11
4,FKID000004,12.977767,77.580545,"Kalidasa Road, Gandhinagar, Nehru Nagar, Benga...",FKN00GL0004,TANKER,NaN,"[""NO PARKING""]",[113],2023-11-22 04:56:46+00:00,...,NaN,FKN00GL0004,TANKER,approved,2023-11-30 03:11:32.796+00,2023-11-22 10:26:46+05:30,2023-11-22,10,2,11

In [4]:
risk_data = (
    df[df["junction_name"] != "No Junction"]
    .groupby(
        [
            "junction_name",
            "police_station",
            "date",
            "hour_ist"
        ]
    )
    .size()
    .reset_index(name="violations")
)

risk_data["day_of_week"] = pd.to_datetime(
    risk_data["date"]
).dt.dayofweek

risk_data["month"] = pd.to_datetime(
    risk_data["date"]
).dt.month

risk_data["day"] = pd.to_datetime(
    risk_data["date"]
).dt.day

print(risk_data.shape)
risk_data.head()

(33955, 8)

,junction_name,police_station,date,hour_ist,violations,day_of_week,month,day
0,"BTP001 - 10th Cross, Dr. Rajkumar Road",Malleshwaram,2023-11-10,6,2,4,11,10
1,"BTP001 - 10th Cross, Dr. Rajkumar Road",Malleshwaram,2023-11-10,11,2,4,11,10
2,"BTP001 - 10th Cross, Dr. Rajkumar Road",Malleshwaram,2023-11-10,13,1,4,11,10
3,"BTP001 - 10th Cross, Dr. Rajkumar Road",Malleshwaram,2023-11-11,3,1,5,11,11
4,"BTP001 - 10th Cross, Dr. Rajkumar Road",Malleshwaram,2023-11-11,6,6,5,11,11

In [5]:
print(
    risk_data["junction_name"]
    .nunique()
)

print(
    risk_data["police_station"]
    .nunique()
)

168
30

In [6]:
# Average violations per junction per hour

hourly_risk = (
    risk_data
    .groupby(
        ["junction_name", "hour_ist"]
    )["violations"]
    .mean()
    .reset_index()
)

hourly_risk.head()

                            junction_name  hour_ist  violations
0  BTP001 - 10th Cross, Dr. Rajkumar Road         0    2.250000
1  BTP001 - 10th Cross, Dr. Rajkumar Road         1    3.714286
2  BTP001 - 10th Cross, Dr. Rajkumar Road         2    5.153846
3  BTP001 - 10th Cross, Dr. Rajkumar Road         3    4.156863
4  BTP001 - 10th Cross, Dr. Rajkumar Road         4    4.800000

In [7]:
# Normalize risk inside each junction

hourly_risk["risk_score"] = (
    hourly_risk.groupby("junction_name")["violations"]
    .transform(
        lambda x: x / x.max()
    )
)

hourly_risk.head()

                            junction_name  hour_ist  violations  risk_score
0  BTP001 - 10th Cross, Dr. Rajkumar Road         0    2.250000    0.204545
1  BTP001 - 10th Cross, Dr. Rajkumar Road         1    3.714286    0.337662
2  BTP001 - 10th Cross, Dr. Rajkumar Road         2    5.153846    0.468531
3  BTP001 - 10th Cross, Dr. Rajkumar Road         3    4.156863    0.377897
4  BTP001 - 10th Cross, Dr. Rajkumar Road         4    4.800000    0.436364

In [8]:
print(hourly_risk.shape)

hourly_risk.sort_values(
    "risk_score",
    ascending=False
).head(20)

(2291, 4)

,junction_name,hour_ist,violations,risk_score
24,BTP006 - Navarang Bar Junction,7,6.000000,1.0
18,"BTP001 - 10th Cross, Dr. Rajkumar Road",18,11.000000,1.0
1636,"BTP164 - 29th Main Road, BTM Layout",3,4.666667,1.0
616,"BTP062 - Basava Mantapa, Dr. Rajkumar Road",0,4.000000,1.0
609,BTP061 - Bhashyam Circle,7,5.916667,1.0
1630,"BTP163 - 16th Main Road, BTM Layout",10,4.636364,1.0
587,BTP058 - Subbanna Junction,1,12.844660,1.0
53,BTP009 - Prakash Nagar Junction,12,21.000000,1.0
70,"BTP011 - RR Kalyana Mantapa, Dr. Rajkumar Road",1,16.923077,1.0
35,BTP008 - Navarang Theatre,8,4.255814,1.0
2238,"BTP221 - 15th Cross, 24th Main, JP Nagar",7,4.000000,1.0
577,BTP057 - Anand Rao Junction,9,6.363636,1.0
1684,"BTP170 - Dr. Bheem Rao Palace, Chord Road",0,22.000000,1.0
1670,"BTP168 - MSR Building, JC Road",0,5.000000,1.0
633,BTP063 - Siddalingaiah Circle,2,4.300000,1.0
1615,"BTP161 - 15th Cross, 35th Main, JP Nagar",3,4.000000,1.0
1705,BTP171 - Indian Express (Balekundri),8,4.000000,1.0
1604,"BTP159 - JP Nagar Metro, ORR",5,2.500000,1.0
656,BTP064 - Devanga Hostel Junction,11,2.500000,1.0
90,"BTP015 - Suguna Hospital, Dr. Rajkumar Road",6,7.000000,1.0

In [9]:
from sklearn.preprocessing import MinMaxScaler

junction_volume = (
    risk_data.groupby("junction_name")["violations"]
    .sum()
    .reset_index(name="total_violations")
)

scaler = MinMaxScaler()

junction_volume["volume_score"] = scaler.fit_transform(
    junction_volume[["total_violations"]]
)

junction_volume.head()

                            junction_name  total_violations  volume_score
0  BTP001 - 10th Cross, Dr. Rajkumar Road              2812      0.181700
1          BTP006 - Navarang Bar Junction                47      0.002655
2               BTP008 - Navarang Theatre              1190      0.076669
3         BTP009 - Prakash Nagar Junction               262      0.016577
4           BTP010 - Rajajinagar Entrance               957      0.061581

In [10]:
hourly_risk_final = hourly_risk.merge(
    junction_volume,
    on="junction_name",
    how="left"
)

hourly_risk_final.head()

,junction_name,hour_ist,violations,risk_score,total_violations,volume_score
0,"BTP001 - 10th Cross, Dr. Rajkumar Road",0,2.250000,0.204545,2812,0.1817
1,"BTP001 - 10th Cross, Dr. Rajkumar Road",1,3.714286,0.337662,2812,0.1817
2,"BTP001 - 10th Cross, Dr. Rajkumar Road",2,5.153846,0.468531,2812,0.1817
3,"BTP001 - 10th Cross, Dr. Rajkumar Road",3,4.156863,0.377897,2812,0.1817
4,"BTP001 - 10th Cross, Dr. Rajkumar Road",4,4.800000,0.436364,2812,0.1817

In [13]:
print(hourly_risk_final.columns.tolist())

['junction_name', 'hour_ist', 'violations', 'risk_score', 'total_violations', 'volume_score']

In [14]:
hourly_risk_final["city_risk"] = (
    0.60 * hourly_risk_final["risk_score"]
    +
    0.40 * hourly_risk_final["volume_score"]
)

print(hourly_risk_final.columns)

Index(['junction_name', 'hour_ist', 'violations', 'risk_score',
       'total_violations', 'volume_score', 'city_risk'],
      dtype='object')

In [15]:
hourly_risk_final.sort_values(
    "city_risk",
    ascending=False
)[
    [
        "junction_name",
        "hour_ist",
        "violations",
        "risk_score",
        "volume_score",
        "city_risk"
    ]
].head(30)

,junction_name,hour_ist,violations,risk_score,volume_score,city_risk
520,BTP051 - Safina Plaza Junction,10,20.433333,1.000000,1.000000,1.000000
521,BTP051 - Safina Plaza Junction,11,17.154362,0.839528,1.000000,0.903717
518,BTP051 - Safina Plaza Junction,8,17.107692,0.837244,1.000000,0.902347
832,BTP082 - KR Market Junction,0,10.043478,1.000000,0.746746,0.898698
382,BTP040 - Elite Junction,9,14.111111,1.000000,0.693648,0.877459
448,BTP044 - Sagar Theatre Junction,9,10.797386,1.000000,0.682704,0.873082
854,BTP082 - KR Market Junction,23,9.065217,0.902597,0.746746,0.840257
849,BTP082 - KR Market Junction,18,9.000000,0.896104,0.746746,0.836361
519,BTP051 - Safina Plaza Junction,9,14.817568,0.725166,1.000000,0.835100
447,BTP044 - Sagar Theatre Junction,8,10.007519,0.926846,0.682704,0.829190
853,BTP082 - KR Market Junction,22,8.870968,0.883257,0.746746,0.828652
381,BTP040 - Elite Junction,8,12.103448,0.857725,0.693648,0.792094
841,BTP082 - KR Market Junction,9,7.791946,0.775821,0.746746,0.764191
449,BTP044 - Sagar Theatre Junction,10,8.727891,0.808334,0.682704,0.758082
2124,BTP211 - Central Street Junction,18,28.500000,1.000000,0.348507,0.739403
833,BTP082 - KR Market Junction,1,7.294118,0.726254,0.746746,0.734451
587,BTP058 - Subbanna Junction,1,12.844660,1.000000,0.335621,0.734249
236,BTP027 - Modi Bridge Junction,7,7.623529,1.000000,0.296445,0.718578
379,BTP040 - Elite Junction,6,10.371134,0.734962,0.693648,0.718436
840,BTP082 - KR Market Junction,8,6.951220,0.692113,0.746746,0.713966
842,BTP082 - KR Market Junction,10,6.857143,0.682746,0.746746,0.708346
144,BTP020 - Hosahalli Metro Station,4,15.652174,1.000000,0.265169,0.706067
383,BTP040 - Elite Junction,10,10.062500,0.713091,0.693648,0.705313
577,BTP057 - Anand Rao Junction,9,6.363636,1.000000,0.254419,0.701768
825,"BTP080 - NR Road, SP Road Junction",10,7.326087,1.000000,0.237972,0.695189
384,BTP040 - Elite Junction,11,9.723810,0.689089,0.693648,0.690912
466,BTP045 - Danvanthri Road Junction,10,4.585366,1.000000,0.205595,0.682238
465,BTP045 - Danvanthri Road Junction,9,4.563380,0.995205,0.205595,0.679361
237,BTP027 - Modi Bridge Junction,8,7.109756,0.932607,0.296445,0.678142
467,BTP045 - Danvanthri Road Junction,11,4.525641,0.986975,0.205595,0.674423

In [16]:
def recommend_deployment(current_hour, officers_available=20, top_n=10):

    current_risk = hourly_risk_final[
        hourly_risk_final["hour_ist"] == current_hour
    ].copy()

    current_risk = current_risk.sort_values(
        "city_risk",
        ascending=False
    )

    current_risk = current_risk.head(top_n)

    total_risk = current_risk["city_risk"].sum()

    current_risk["recommended_officers"] = (
        current_risk["city_risk"] / total_risk
        * officers_available
    ).round()

    current_risk["recommended_officers"] = (
        current_risk["recommended_officers"]
        .clip(lower=1)
        .astype(int)
    )

    return current_risk[
        [
            "junction_name",
            "city_risk",
            "recommended_officers"
        ]
    ]


deployment_10am = recommend_deployment(
    current_hour=10,
    officers_available=20
)

deployment_10am

                            junction_name  city_risk  recommended_officers
520        BTP051 - Safina Plaza Junction   1.000000                     3
449       BTP044 - Sagar Theatre Junction   0.758082                     2
842           BTP082 - KR Market Junction   0.708346                     2
383               BTP040 - Elite Junction   0.705313                     2
825    BTP080 - NR Road, SP Road Junction   0.695189                     2
466     BTP045 - Danvanthri Road Junction   0.682238                     2
180    BTP023 - Mahalaxmi Layout Entrance   0.646649                     2
2165         BTP215 - Vanivillas Junction   0.611086                     2
665          BTP067 - Jai Muni Rao Circle   0.610438                     2
1630  BTP163 - 16th Main Road, BTM Layout   0.609273                     2

In [17]:
deployment_8am = recommend_deployment(8,20)

deployment_8am

                             junction_name  city_risk  recommended_officers
518         BTP051 - Safina Plaza Junction   0.902347                     3
447        BTP044 - Sagar Theatre Junction   0.829190                     2
381                BTP040 - Elite Junction   0.792094                     2
840            BTP082 - KR Market Junction   0.713966                     2
237          BTP027 - Modi Bridge Junction   0.678142                     2
148       BTP020 - Hosahalli Metro Station   0.664639                     2
413   BTP042 - Minsk Square Junction (CTO)   0.635255                     2
35               BTP008 - Navarang Theatre   0.630668                     2
692                     BTP069 - MC Circle   0.627689                     2
2038       BTP205 - Modi Hospital Junction   0.626912                     2

In [18]:
deployment_6pm = recommend_deployment(18,20)

deployment_6pm

                               junction_name  city_risk  recommended_officers
849              BTP082 - KR Market Junction   0.836361                     4
2124        BTP211 - Central Street Junction   0.739403                     4
18    BTP001 - 10th Cross, Dr. Rajkumar Road   0.672680                     3
245            BTP027 - Modi Bridge Junction   0.512097                     3
1410              BTP135 - UCO Bank Junction   0.405255                     2
112       BTP016 - 5th Main Road, RPC Layout   0.243925                     1
474        BTP045 - Danvanthri Road Junction   0.213089                     1
1480            BTP140 - Madiwala Check Post   0.209376                     1
932     BTP092 - Bangalore Builders Junction   0.140793                     1
1445   BTP137 - Madiwala Traffic PS Junction   0.109770                     1

In [19]:
def calculate_expected_impact(row):

    risk = row["city_risk"]
    officers = row["recommended_officers"]

    violation_reduction = (
        risk * officers * 12
    )

    congestion_reduction = min(
        60,
        round(risk * officers * 8)
    )

    if risk >= 0.80:
        priority = "CRITICAL"

    elif risk >= 0.60:
        priority = "HIGH"

    elif risk >= 0.40:
        priority = "MEDIUM"

    else:
        priority = "LOW"

    return pd.Series([
        round(violation_reduction),
        congestion_reduction,
        priority
    ])


deployment_live = recommend_deployment(
    current_hour=10,
    officers_available=20
)

deployment_live[
    [
        "expected_violations_prevented",
        "expected_congestion_reduction",
        "priority"
    ]
] = deployment_live.apply(
    calculate_expected_impact,
    axis=1
)

deployment_live

,junction_name,city_risk,recommended_officers,expected_violations_prevented,expected_congestion_reduction,priority
520,BTP051 - Safina Plaza Junction,1.000000,3,36,24,CRITICAL
449,BTP044 - Sagar Theatre Junction,0.758082,2,18,12,HIGH
842,BTP082 - KR Market Junction,0.708346,2,17,11,HIGH
383,BTP040 - Elite Junction,0.705313,2,17,11,HIGH
825,"BTP080 - NR Road, SP Road Junction",0.695189,2,17,11,HIGH
466,BTP045 - Danvanthri Road Junction,0.682238,2,16,11,HIGH
180,BTP023 - Mahalaxmi Layout Entrance,0.646649,2,16,10,HIGH
2165,BTP215 - Vanivillas Junction,0.611086,2,15,10,HIGH
665,BTP067 - Jai Muni Rao Circle,0.610438,2,15,10,HIGH
1630,"BTP163 - 16th Main Road, BTM Layout",0.609273,2,15,10,HIGH

In [20]:
deployment_live.head(10)

,junction_name,city_risk,recommended_officers,expected_violations_prevented,expected_congestion_reduction,priority
520,BTP051 - Safina Plaza Junction,1.000000,3,36,24,CRITICAL
449,BTP044 - Sagar Theatre Junction,0.758082,2,18,12,HIGH
842,BTP082 - KR Market Junction,0.708346,2,17,11,HIGH
383,BTP040 - Elite Junction,0.705313,2,17,11,HIGH
825,"BTP080 - NR Road, SP Road Junction",0.695189,2,17,11,HIGH
466,BTP045 - Danvanthri Road Junction,0.682238,2,16,11,HIGH
180,BTP023 - Mahalaxmi Layout Entrance,0.646649,2,16,10,HIGH
2165,BTP215 - Vanivillas Junction,0.611086,2,15,10,HIGH
665,BTP067 - Jai Muni Rao Circle,0.610438,2,15,10,HIGH
1630,"BTP163 - 16th Main Road, BTM Layout",0.609273,2,15,10,HIGH

In [21]:

station_daily = df.groupby(['police_station','date']).agg(
    violations=('id','count')
).reset_index()

station_junction_count = df.groupby('police_station')['junction_name'].nunique().rename('junction_count')
station_daily = station_daily.join(station_junction_count, on='police_station')
station_daily['violations_per_junction'] = station_daily['violations'] / station_daily['junction_count']

avg_reduction = station_daily['violations_per_junction'].mean()
print(f"Average violations per junction per day: {avg_reduction:.1f}")

Average violations per junction per day: 15.2

In [22]:
import os
files = ['junction_pdi.csv', 'junction_behavior.csv', 
         'cluster_hotspots.csv', 'station_eps.csv']
for f in files:
    print(f, '→', os.path.exists(f))

junction_pdi.csv → True
junction_behavior.csv → True
cluster_hotspots.csv → True
station_eps.csv → True

In [23]:
hourly_risk_final.to_csv('hourly_risk_final.csv', index=False)
print("Saved!", hourly_risk_final.shape)

Saved! (2291, 7)

In [24]:
import os
print([f for f in os.listdir('.') if f.endswith('.csv')])

['cluster_hotspots.csv', 'hourly_risk_final.csv', 'jan to may police violation_anonymized791b166.csv', 'junction_behavior.csv', 'junction_hourly.csv', 'junction_pdi.csv', 'station_eps.csv']

In [25]:
named_df = df[
    df['junction_name'].str.strip() != 'No Junction'
].copy()

print(named_df.shape)
print(named_df['junction_name'].nunique())

(150570, 29)
168

In [26]:
from sklearn.preprocessing import MinMaxScaler
import pandas as pd
import numpy as np

# PDI REBUILD (WITHOUT NO JUNCTION)

junction_total = (
    named_df.groupby("junction_name")
    .size()
    .rename("total_violations")
)

junction_active_days = (
    named_df.groupby("junction_name")["date"]
    .nunique()
    .rename("active_days")
)

junction_peak = (
    named_df[named_df["hour_ist"].between(8,11)]
    .groupby("junction_name")
    .size()
    .rename("peak_violations")
)

heavy_types = [
    "HGV",
    "LORRY/GOODS VEHICLE",
    "TANKER",
    "PRIVATE BUS",
    "BUS (BMTC/KSRTC)",
    "TOURIST BUS",
    "SCHOOL VEHICLE"
]

junction_heavy = (
    named_df[named_df["vehicle_type"].isin(heavy_types)]
    .groupby("junction_name")
    .size()
    .rename("heavy_violations")
)

pdi = pd.concat([
    junction_total,
    junction_active_days,
    junction_peak,
    junction_heavy
], axis=1).fillna(0)

pdi["peak_ratio"] = (
    pdi["peak_violations"] /
    pdi["total_violations"]
)

pdi["heavy_ratio"] = (
    pdi["heavy_violations"] /
    pdi["total_violations"]
)

pdi["recurrence"] = (
    pdi["total_violations"] /
    pdi["active_days"]
)

scaler = MinMaxScaler()

pdi[[
    "freq_n",
    "peak_n",
    "heavy_n",
    "recur_n"
]] = scaler.fit_transform(
    pdi[[
        "total_violations",
        "peak_ratio",
        "heavy_ratio",
        "recurrence"
    ]]
)

pdi["PDI"] = (
      0.40 * pdi["freq_n"]
    + 0.25 * pdi["peak_n"]
    + 0.20 * pdi["heavy_n"]
    + 0.15 * pdi["recur_n"]
) * 100

pdi = pdi.sort_values(
    "PDI",
    ascending=False
)

print(pdi[[
    "total_violations",
    "peak_ratio",
    "heavy_ratio",
    "PDI"
]].head(20))

                                            total_violations  peak_ratio  \
junction_name
BTP051 - Safina Plaza Junction                         15449    0.649751
BTP044 - Sagar Theatre Junction                        10549    0.494834
BTP040 - Elite Junction                                10718    0.485445
BTP082 - KR Market Junction                            11538    0.345120
BTP211 - Central Street Junction                        5388    0.435226
BTP080 - NR Road, SP Road Junction                      3681    0.545504
BTP027 - Modi Bridge Junction                           4584    0.428447
BTP057 - Anand Rao Junction                             3935    0.364676
BTP023 - Mahalaxmi Layout Entrance                      1807    0.551190
BTP020 - Hosahalli Metro Station                        4101    0.366496
BTP045 - Danvanthri Road Junction                       3181    0.412449
BTP212 - Minto Junction                                   78    0.564103
BTP058 - Subbanna Junction                              5189    0.259202
BTP178 - 18th Main, Marenahalli                            7    0.571429
BTP038 - Mysore Bank Junction                           2021    0.512618
BTP053 - Three Let Junction                               51    0.627451
BTP070 - Cholurpalya Junction, Magadi Road              2272    0.452025
BTP219 - Canara Bank Junction                            358    0.628492
BTP102 - BMTC Junction, KH Road                          175    0.634286
BTP143 - ASC Junction                                     24    0.125000

                                            heavy_ratio        PDI
junction_name
BTP051 - Safina Plaza Junction                 0.001295  80.051783
BTP044 - Sagar Theatre Junction                0.013840  57.089801
BTP040 - Elite Junction                        0.004385  56.954042
BTP082 - KR Market Junction                    0.003900  54.464576
BTP211 - Central Street Junction               0.003712  36.026741
BTP080 - NR Road, SP Road Junction             0.008693  34.529600
BTP027 - Modi Bridge Junction                  0.001527  32.826765
BTP057 - Anand Rao Junction                    0.059466  30.359478
BTP023 - Mahalaxmi Layout Entrance             0.065855  30.264867
BTP020 - Hosahalli Metro Station               0.001463  29.581207
BTP045 - Danvanthri Road Junction              0.052185  29.197992
BTP212 - Minto Junction                        0.166667  28.938992
BTP058 - Subbanna Junction                     0.012334  28.850965
BTP178 - 18th Main, Marenahalli                0.142857  27.793347
BTP038 - Mysore Bank Junction                  0.018803  27.745089
BTP053 - Three Let Junction                    0.058824  26.757105
BTP070 - Cholurpalya Junction, Magadi Road     0.002201  26.109390
BTP219 - Canara Bank Junction                  0.000000  25.556220
BTP102 - BMTC Junction, KH Road                0.011429  25.485830
BTP143 - ASC Junction                          0.500000  25.042553

In [27]:
print(pdi.head(20))

                                            total_violations  active_days  \
junction_name
BTP051 - Safina Plaza Junction                         15449          151
BTP044 - Sagar Theatre Junction                        10549          151
BTP040 - Elite Junction                                10718          151
BTP082 - KR Market Junction                            11538          151
BTP211 - Central Street Junction                        5388          149
BTP080 - NR Road, SP Road Junction                      3681          142
BTP027 - Modi Bridge Junction                           4584          148
BTP057 - Anand Rao Junction                             3935          148
BTP023 - Mahalaxmi Layout Entrance                      1807          139
BTP020 - Hosahalli Metro Station                        4101          122
BTP045 - Danvanthri Road Junction                       3181          148
BTP212 - Minto Junction                                   78           21
BTP058 - Subbanna Junction                              5189          150
BTP178 - 18th Main, Marenahalli                            7            4
BTP038 - Mysore Bank Junction                           2021          135
BTP053 - Three Let Junction                               51           24
BTP070 - Cholurpalya Junction, Magadi Road              2272          115
BTP219 - Canara Bank Junction                            358           84
BTP102 - BMTC Junction, KH Road                          175           73
BTP143 - ASC Junction                                     24           10

                                            peak_violations  heavy_violations  \
junction_name
BTP051 - Safina Plaza Junction                      10038.0              20.0
BTP044 - Sagar Theatre Junction                      5220.0             146.0
BTP040 - Elite Junction                              5203.0              47.0
BTP082 - KR Market Junction                          3982.0              45.0
BTP211 - Central Street Junction                     2345.0              20.0
BTP080 - NR Road, SP Road Junction                   2008.0              32.0
BTP027 - Modi Bridge Junction                        1964.0               7.0
BTP057 - Anand Rao Junction                          1435.0             234.0
BTP023 - Mahalaxmi Layout Entrance                    996.0             119.0
BTP020 - Hosahalli Metro Station                     1503.0               6.0
BTP045 - Danvanthri Road Junction                    1312.0             166.0
BTP212 - Minto Junction                                44.0              13.0
BTP058 - Subbanna Junction                           1345.0              64.0
BTP178 - 18th Main, Marenahalli                         4.0               1.0
BTP038 - Mysore Bank Junction                        1036.0              38.0
BTP053 - Three Let Junction                            32.0               3.0
BTP070 - Cholurpalya Junction, Magadi Road           1027.0               5.0
BTP219 - Canara Bank Junction                         225.0               0.0
BTP102 - BMTC Junction, KH Road                       111.0               2.0
BTP143 - ASC Junction                                   3.0              12.0

                                            peak_ratio  heavy_ratio  \
junction_name
BTP051 - Safina Plaza Junction                0.649751     0.001295
BTP044 - Sagar Theatre Junction               0.494834     0.013840
BTP040 - Elite Junction                       0.485445     0.004385
BTP082 - KR Market Junction                   0.345120     0.003900
BTP211 - Central Street Junction              0.435226     0.003712
BTP080 - NR Road, SP Road Junction            0.545504     0.008693
BTP027 - Modi Bridge Junction                 0.428447     0.001527
BTP057 - Anand Rao Junction                   0.364676     0.059466
BTP023 - Mahalaxmi Layout Entrance            0.551190     0.065855
BTP020 - Hosahalli Metro Station              0.366496     0.001463
BTP045 - Danvanthri Road Junction             0.412449     0.052185
BTP212 - Minto Junction                       0.564103     0.166667
BTP058 - Subbanna Junction                    0.259202     0.012334
BTP178 - 18th Main, Marenahalli               0.571429     0.142857
BTP038 - Mysore Bank Junction                 0.512618     0.018803
BTP053 - Three Let Junction                   0.627451     0.058824
BTP070 - Cholurpalya Junction, Magadi Road    0.452025     0.002201
BTP219 - Canara Bank Junction                 0.628492     0.000000
BTP102 - BMTC Junction, KH Road               0.634286     0.011429
BTP143 - ASC Junction                         0.125000     0.500000

                                            recurrence    freq_n    peak_n  \
junction_name
BTP051 - Safina Plaza Junction              102.311258  1.000000  1.000000
BTP044 - Sagar Theatre Junction              69.860927  0.682704  0.761574
BTP040 - Elite Junction                      70.980132  0.693648  0.747125
BTP082 - KR Market Junction                  76.410596  0.746746  0.531158
BTP211 - Central Street Junction             36.161074  0.348507  0.669836
BTP080 - NR Road, SP Road Junction           25.922535  0.237972  0.839559
BTP027 - Modi Bridge Junction                30.972973  0.296445  0.659402
BTP057 - Anand Rao Junction                  26.587838  0.254419  0.561255
BTP023 - Mahalaxmi Layout Entrance           13.000000  0.116622  0.848310
BTP020 - Hosahalli Metro Station             33.614754  0.265169  0.564056
BTP045 - Danvanthri Road Junction            21.493243  0.205595  0.634780
BTP212 - Minto Junction                       3.714286  0.004662  0.868183
BTP058 - Subbanna Junction                   34.593333  0.335621  0.398925
BTP178 - 18th Main, Marenahalli               1.750000  0.000065  0.879458
BTP038 - Mysore Bank Junction                14.970370  0.130480  0.788945
BTP053 - Three Let Junction                   2.125000  0.002914  0.965679
BTP070 - Cholurpalya Junction, Magadi Road   19.756522  0.146733  0.695689
BTP219 - Canara Bank Junction                 4.261905  0.022793  0.967281
BTP102 - BMTC Junction, KH Road               2.397260  0.010943  0.976198
BTP143 - ASC Junction                         2.400000  0.001166  0.192381

                                             heavy_n   recur_n        PDI
junction_name
BTP051 - Safina Plaza Junction              0.002589  1.000000  80.051783
BTP044 - Sagar Theatre Junction             0.027680  0.679244  57.089801
BTP040 - Elite Junction                     0.008770  0.690307  56.954042
BTP082 - KR Market Junction                 0.007800  0.743985  54.464576
BTP211 - Central Street Junction            0.007424  0.346138  36.026741
BTP080 - NR Road, SP Road Junction          0.017387  0.244935  34.529600
BTP027 - Modi Bridge Junction               0.003054  0.294856  32.826765
BTP057 - Anand Rao Junction                 0.118933  0.251511  30.359478
BTP023 - Mahalaxmi Layout Entrance          0.131710  0.117202  30.264867
BTP020 - Hosahalli Metro Station            0.002926  0.320969  29.581207
BTP045 - Danvanthri Road Junction           0.104370  0.201154  29.197992
BTP212 - Minto Junction                     0.333333  0.025417  28.938992
BTP058 - Subbanna Junction                  0.024668  0.330642  28.850965
BTP178 - 18th Main, Marenahalli             0.285714  0.006001  27.793347
BTP038 - Mysore Bank Junction               0.037605  0.136678  27.745089
BTP053 - Three Let Junction                 0.117647  0.009708  26.757105
BTP070 - Cholurpalya Junction, Magadi Road  0.004401  0.183987  26.109390
BTP219 - Canara Bank Junction               0.000000  0.030830  25.556220
BTP102 - BMTC Junction, KH Road             0.022857  0.012399  25.485830
BTP143 - ASC Junction                       1.000000  0.012426  25.042553

In [28]:
print(named_df.shape)

print(
    named_df["junction_name"]
    .nunique()
)

(150570, 29)
168

In [29]:
import pandas as pd
import numpy as np

# Daily violations per junction

daily_counts = (
    named_df
    .groupby(["junction_name", "date"])
    .size()
    .reset_index(name="daily_violations")
)

daily_counts.head()

                            junction_name        date  daily_violations
0  BTP001 - 10th Cross, Dr. Rajkumar Road  2023-11-10                 5
1  BTP001 - 10th Cross, Dr. Rajkumar Road  2023-11-11                20
2  BTP001 - 10th Cross, Dr. Rajkumar Road  2023-11-12                 2
3  BTP001 - 10th Cross, Dr. Rajkumar Road  2023-11-13                 8
4  BTP001 - 10th Cross, Dr. Rajkumar Road  2023-11-14                15

In [30]:
junction_behavior = daily_counts.groupby(
    "junction_name"
).agg(
    daily_avg=("daily_violations", "mean"),
    daily_std=("daily_violations", "std"),
    daily_max=("daily_violations", "max"),
    active_days=("daily_violations", "count")
).reset_index()

junction_behavior["consistency"] = (
    1 -
    (
        junction_behavior["daily_std"]
        /
        junction_behavior["daily_avg"]
    )
).clip(0, 1)

junction_behavior["spike_ratio"] = (
    junction_behavior["daily_max"]
    /
    junction_behavior["daily_avg"]
)

junction_behavior = junction_behavior.fillna(0)

junction_behavior.head()

,junction_name,daily_avg,daily_std,daily_max,active_days,consistency,spike_ratio
0,"BTP001 - 10th Cross, Dr. Rajkumar Road",20.085714,17.579618,84,140,0.124770,4.182077
1,BTP006 - Navarang Bar Junction,3.357143,2.924884,9,14,0.128758,2.680851
2,BTP008 - Navarang Theatre,10.000000,10.738810,66,119,-0.073881,6.600000
3,BTP009 - Prakash Nagar Junction,7.705882,14.381237,74,34,-0.866267,9.603053
4,BTP010 - Rajajinagar Entrance,7.656000,8.027276,60,125,-0.048495,7.836991

In [31]:
daily_counts["week"] = (
    pd.to_datetime(daily_counts["date"])
    .dt.isocalendar()
    .week
)

weekly = (
    daily_counts
    .groupby(
        ["junction_name", "week"]
    )["daily_violations"]
    .sum()
    .reset_index()
)

growth_data = []

for junction in weekly["junction_name"].unique():

    temp = weekly[
        weekly["junction_name"] == junction
    ]

    if len(temp) < 8:
        growth = 0

    else:

        first4 = temp.head(4)["daily_violations"].mean()
        last4 = temp.tail(4)["daily_violations"].mean()

        growth = (
            (last4 - first4)
            /
            max(first4, 1)
        )

    growth_data.append(
        [junction, growth]
    )

growth_df = pd.DataFrame(
    growth_data,
    columns=[
        "junction_name",
        "growth_rate"
    ]
)

junction_behavior = junction_behavior.merge(
    growth_df,
    on="junction_name",
    how="left"
)

junction_behavior.head()

,junction_name,daily_avg,daily_std,daily_max,active_days,consistency,spike_ratio,growth_rate
0,"BTP001 - 10th Cross, Dr. Rajkumar Road",20.085714,17.579618,84,140,0.124770,4.182077,-0.302832
1,BTP006 - Navarang Bar Junction,3.357143,2.924884,9,14,0.128758,2.680851,-0.210526
2,BTP008 - Navarang Theatre,10.000000,10.738810,66,119,-0.073881,6.600000,1.361538
3,BTP009 - Prakash Nagar Junction,7.705882,14.381237,74,34,-0.866267,9.603053,-0.796296
4,BTP010 - Rajajinagar Entrance,7.656000,8.027276,60,125,-0.048495,7.836991,0.160584

In [32]:
junction_behavior.describe()

,daily_avg,daily_std,daily_max,active_days,consistency,spike_ratio,growth_rate
count,168.000000,168.000000,168.000000,168.000000,168.000000,168.000000,168.000000
mean,8.538021,8.223415,43.571429,67.041667,-0.046797,5.330394,0.558966
std,13.126319,9.957480,56.977732,42.458483,0.338455,2.414645,1.469416
min,1.142857,0.377964,2.000000,3.000000,-1.527144,1.500000,-0.886792
25%,3.071227,2.977214,13.000000,33.000000,-0.167901,3.565430,-0.251410
50%,4.293285,5.346804,26.000000,58.500000,-0.018664,4.760723,0.120640
75%,8.512246,9.969194,52.250000,103.000000,0.176980,6.701965,0.743071
max,102.311258,84.370705,459.000000,151.000000,0.669281,15.651639,9.666667

In [33]:
junction_behavior.sort_values(
    "daily_avg",
    ascending=False
).head(15)

,junction_name,daily_avg,daily_std,daily_max,active_days,consistency,spike_ratio,growth_rate
34,BTP051 - Safina Plaza Junction,102.311258,84.370705,459,151,0.175353,4.486310,-0.365001
56,BTP082 - KR Market Junction,76.410596,45.922147,230,151,0.399008,3.010054,-0.276556
26,BTP040 - Elite Junction,70.980132,41.962439,241,151,0.408814,3.395316,0.061473
30,BTP044 - Sagar Theatre Junction,69.860927,40.857646,222,151,0.415157,3.177742,-0.269088
154,BTP211 - Central Street Junction,36.161074,38.905997,237,149,-0.075908,6.554009,-0.597623
39,BTP058 - Subbanna Junction,34.593333,24.722106,119,150,0.285351,3.439969,0.260684
10,BTP020 - Hosahalli Metro Station,33.614754,38.684023,294,122,-0.150805,8.746159,0.590705
16,BTP027 - Modi Bridge Junction,30.972973,27.876537,167,148,0.099972,5.391798,0.390177
38,BTP057 - Anand Rao Junction,26.587838,18.346598,91,148,0.309963,3.422618,0.284703
19,BTP032 - Windsor Circle,25.933962,28.860343,166,106,-0.112840,6.400873,0.746479
55,"BTP080 - NR Road, SP Road Junction",25.922535,23.883605,115,142,0.078655,4.436294,0.370588
7,"BTP016 - 5th Main Road, RPC Layout",24.019417,22.694035,110,103,0.055180,4.579628,0.563131
31,BTP045 - Danvanthri Road Junction,21.493243,16.526827,109,148,0.231069,5.071361,0.129549
0,"BTP001 - 10th Cross, Dr. Rajkumar Road",20.085714,17.579618,84,140,0.124770,4.182077,-0.302832
57,"BTP083 - AS Char Street, Mysore Road",19.985612,17.315899,76,139,0.133582,3.802736,-0.001718

In [34]:
behavior_df = junction_behavior.copy()

conditions = []

for _, row in behavior_df.iterrows():

    avg = row["daily_avg"]
    growth = row["growth_rate"]
    spike = row["spike_ratio"]

    if avg >= 40:
        conditions.append("PERSISTENT")

    elif growth >= 0.5:
        conditions.append("EMERGING")

    elif spike >= 6:
        conditions.append("BURST")

    else:
        conditions.append("STABLE")

behavior_df["hotspot_type"] = conditions

behavior_df["priority_level"] = np.where(
    behavior_df["daily_avg"] >= 50,
    "CRITICAL",
    np.where(
        behavior_df["daily_avg"] >= 20,
        "HIGH",
        np.where(
            behavior_df["daily_avg"] >= 8,
            "MEDIUM",
            "LOW"
        )
    )
)

behavior_df[
    [
        "junction_name",
        "daily_avg",
        "growth_rate",
        "spike_ratio",
        "hotspot_type",
        "priority_level"
    ]
].sort_values(
    "daily_avg",
    ascending=False
).head(30)

,junction_name,daily_avg,growth_rate,spike_ratio,hotspot_type,priority_level
34,BTP051 - Safina Plaza Junction,102.311258,-0.365001,4.486310,PERSISTENT,CRITICAL
56,BTP082 - KR Market Junction,76.410596,-0.276556,3.010054,PERSISTENT,CRITICAL
26,BTP040 - Elite Junction,70.980132,0.061473,3.395316,PERSISTENT,CRITICAL
30,BTP044 - Sagar Theatre Junction,69.860927,-0.269088,3.177742,PERSISTENT,CRITICAL
154,BTP211 - Central Street Junction,36.161074,-0.597623,6.554009,BURST,HIGH
39,BTP058 - Subbanna Junction,34.593333,0.260684,3.439969,STABLE,HIGH
10,BTP020 - Hosahalli Metro Station,33.614754,0.590705,8.746159,EMERGING,HIGH
16,BTP027 - Modi Bridge Junction,30.972973,0.390177,5.391798,STABLE,HIGH
38,BTP057 - Anand Rao Junction,26.587838,0.284703,3.422618,STABLE,HIGH
19,BTP032 - Windsor Circle,25.933962,0.746479,6.400873,EMERGING,HIGH
55,"BTP080 - NR Road, SP Road Junction",25.922535,0.370588,4.436294,STABLE,HIGH
7,"BTP016 - 5th Main Road, RPC Layout",24.019417,0.563131,4.579628,EMERGING,HIGH
31,BTP045 - Danvanthri Road Junction,21.493243,0.129549,5.071361,STABLE,HIGH
0,"BTP001 - 10th Cross, Dr. Rajkumar Road",20.085714,-0.302832,4.182077,STABLE,HIGH
57,"BTP083 - AS Char Street, Mysore Road",19.985612,-0.001718,3.802736,STABLE,MEDIUM
47,"BTP070 - Cholurpalya Junction, Magadi Road",19.756522,-0.292517,5.213468,STABLE,MEDIUM
28,BTP042 - Minsk Square Junction (CTO),18.925926,-0.305882,5.495108,STABLE,MEDIUM
8,BTP017 - Attiguppe Circle,17.583333,1.844444,2.559242,EMERGING,MEDIUM
25,BTP038 - Mysore Bank Junction,14.970370,0.266968,4.742702,STABLE,MEDIUM
33,BTP048 - Shanthala Junction,13.275000,-0.306931,7.156309,BURST,MEDIUM
12,BTP023 - Mahalaxmi Layout Entrance,13.000000,0.338542,3.615385,STABLE,MEDIUM
72,BTP104 - Medical College Circle,12.888889,-0.134831,4.112069,STABLE,MEDIUM
76,BTP108 - Tagore Park Junction,12.864286,-0.437363,3.964464,STABLE,MEDIUM
29,BTP043 - Upparpet Junction,12.757143,-0.171569,9.249720,BURST,MEDIUM
123,BTP172 - Nanjappa Circle,12.721311,0.245283,5.030928,STABLE,MEDIUM
134,"BTP186 - 9th Cross, 4th Main, Jayanagar",11.617021,-0.162162,4.562271,STABLE,MEDIUM
5,"BTP011 - RR Kalyana Mantapa, Dr. Rajkumar Road",11.504762,-0.255639,4.085265,STABLE,MEDIUM
131,"BTP182 - 19th Main Junction, Rajajinagar",11.487603,0.224215,3.394964,STABLE,MEDIUM
46,BTP069 - MC Circle,11.315789,0.209677,5.125581,STABLE,MEDIUM
15,"BTP026 - 1st Block Junction, Rajajinagar",10.647059,0.238532,3.381215,STABLE,MEDIUM

In [35]:
behavior_df["hotspot_type"].value_counts()

hotspot_type
STABLE        81
EMERGING      51
BURST         32
PERSISTENT     4
Name: count, dtype: int64

In [36]:
behavior_df[
    [
        "junction_name",
        "daily_avg",
        "hotspot_type",
        "priority_level"
    ]
].sort_values(
    "daily_avg",
    ascending=False
).head(25)

,junction_name,daily_avg,hotspot_type,priority_level
34,BTP051 - Safina Plaza Junction,102.311258,PERSISTENT,CRITICAL
56,BTP082 - KR Market Junction,76.410596,PERSISTENT,CRITICAL
26,BTP040 - Elite Junction,70.980132,PERSISTENT,CRITICAL
30,BTP044 - Sagar Theatre Junction,69.860927,PERSISTENT,CRITICAL
154,BTP211 - Central Street Junction,36.161074,BURST,HIGH
39,BTP058 - Subbanna Junction,34.593333,STABLE,HIGH
10,BTP020 - Hosahalli Metro Station,33.614754,EMERGING,HIGH
16,BTP027 - Modi Bridge Junction,30.972973,STABLE,HIGH
38,BTP057 - Anand Rao Junction,26.587838,STABLE,HIGH
19,BTP032 - Windsor Circle,25.933962,EMERGING,HIGH
55,"BTP080 - NR Road, SP Road Junction",25.922535,STABLE,HIGH
7,"BTP016 - 5th Main Road, RPC Layout",24.019417,EMERGING,HIGH
31,BTP045 - Danvanthri Road Junction,21.493243,STABLE,HIGH
0,"BTP001 - 10th Cross, Dr. Rajkumar Road",20.085714,STABLE,HIGH
57,"BTP083 - AS Char Street, Mysore Road",19.985612,STABLE,MEDIUM
47,"BTP070 - Cholurpalya Junction, Magadi Road",19.756522,STABLE,MEDIUM
28,BTP042 - Minsk Square Junction (CTO),18.925926,STABLE,MEDIUM
8,BTP017 - Attiguppe Circle,17.583333,EMERGING,MEDIUM
25,BTP038 - Mysore Bank Junction,14.970370,STABLE,MEDIUM
33,BTP048 - Shanthala Junction,13.275000,BURST,MEDIUM
12,BTP023 - Mahalaxmi Layout Entrance,13.000000,STABLE,MEDIUM
72,BTP104 - Medical College Circle,12.888889,STABLE,MEDIUM
76,BTP108 - Tagore Park Junction,12.864286,STABLE,MEDIUM
29,BTP043 - Upparpet Junction,12.757143,BURST,MEDIUM
123,BTP172 - Nanjappa Circle,12.721311,STABLE,MEDIUM

In [37]:
behavior_df.to_csv(
    "junction_behavior_final.csv",
    index=False
)

print(behavior_df.shape)

(168, 10)

In [40]:
junction_pdi.to_csv("junction_pdi_final.csv")

behavior_df.to_csv("junction_behavior_final.csv")

hourly_risk_final.to_csv(
    "hourly_risk_final.csv",
    index=False
)

NameError: name 'junction_pdi' is not defined

In [41]:
list(globals().keys())

['__name__',
 '__doc__',
 '__package__',
 '__loader__',
 '__spec__',
 '__builtin__',
 '__builtins__',
 '_ih',
 '_oh',
 '_dh',
 'In',
 'Out',
 'get_ipython',
 'exit',
 'quit',
 'open',
 '_',
 '__',
 '___',
 '__vsc_ipynb_file__',
 '_i',
 '_ii',
 '_iii',
 '_i1',
 '_1',
 '_i2',
 '_i3',
 'pd',
 'np',
 'df',
 '_3',
 '_i4',
 'risk_data',
 '_4',
 '_i5',
 '_i6',
 'hourly_risk',
 '_6',
 '_i7',
 '_7',
 '_i8',
 '_8',
 '_i9',
 'MinMaxScaler',
 'junction_volume',
 'scaler',
 '_9',
 '_i10',
 'hourly_risk_final',
 '_10',
 '_i11',
 '_i12',
 '_i13',
 '_i14',
 '_i15',
 '_15',
 '_i16',
 'recommend_deployment',
 'deployment_10am',
 '_16',
 '_i17',
 'deployment_8am',
 '_17',
 '_i18',
 'deployment_6pm',
 '_18',
 '_i19',
 'calculate_expected_impact',
 'deployment_live',
 '_19',
 '_i20',
 '_20',
 '_i21',
 'station_daily',
 'station_junction_count',
 'avg_reduction',
 '_i22',
 'os',
 'files',
 'f',
 '_i23',
 '_i24',
 '_i25',
 'named_df',
 '_i26',
 'junction_total',
 'junction_active_days',
 'junction_peak',
 'heavy_types',
 'junction_heavy',
 'pdi',
 '_i27',
 '_i28',
 '_i29',
 'daily_counts',
 '_29',
 '_i30',
 'junction_behavior',
 '_30',
 '_i31',
 'weekly',
 'growth_data',
 'junction',
 'temp',
 'first4',
 'last4',
 'growth',
 'growth_df',
 '_31',
 '_i32',
 '_32',
 '_i33',
 '_33',
 '_i34',
 'behavior_df',
 'conditions',
 'row',
 'avg',
 'spike',
 '_34',
 '_i35',
 '_35',
 '_i36',
 '_36',
 '_i37',
 'builtins',
 'ipykernel',
 'debugpy',
 '_i38',
 '_i39',
 '_i40',
 '_i41']

In [42]:
print("behavior_df" in globals())
print("hourly_risk_final" in globals())
print("junction_pdi" in globals())

True
True
False

In [43]:
behavior_df.to_csv(
    "junction_behavior_final.csv",
    index=False
)

hourly_risk_final.to_csv(
    "hourly_risk_final.csv",
    index=False
)

print("Saved successfully")

Saved successfully

In [44]:
print("hourly_risk_final shape:")
print(hourly_risk_final.shape)

print("\nbehavior_df shape:")
print(behavior_df.shape)

hourly_risk_final shape:
(2291, 7)

behavior_df shape:
(168, 10)

In [45]:
try:
    print("\n8 AM Deployment")
    print(
        recommend_deployment(8).head(10)
    )

except Exception as e:
    print("8AM Error:", e)


try:
    print("\n10 AM Deployment")
    print(
        recommend_deployment(10).head(10)
    )

except Exception as e:
    print("10AM Error:", e)


try:
    print("\n6 PM Deployment")
    print(
        recommend_deployment(18).head(10)
    )

except Exception as e:
    print("6PM Error:", e)

8 AM Deployment
                             junction_name  city_risk  recommended_officers
518         BTP051 - Safina Plaza Junction   0.902347                     3
447        BTP044 - Sagar Theatre Junction   0.829190                     2
381                BTP040 - Elite Junction   0.792094                     2
840            BTP082 - KR Market Junction   0.713966                     2
237          BTP027 - Modi Bridge Junction   0.678142                     2
148       BTP020 - Hosahalli Metro Station   0.664639                     2
413   BTP042 - Minsk Square Junction (CTO)   0.635255                     2
35               BTP008 - Navarang Theatre   0.630668                     2
692                     BTP069 - MC Circle   0.627689                     2
2038       BTP205 - Modi Hospital Junction   0.626912                     2

10 AM Deployment
                            junction_name  city_risk  recommended_officers
520        BTP051 - Safina Plaza Junction   1.000000                     3
449       BTP044 - Sagar Theatre Junction   0.758082                     2
842           BTP082 - KR Market Junction   0.708346                     2
383               BTP040 - Elite Junction   0.705313                     2
825    BTP080 - NR Road, SP Road Junction   0.695189                     2
466     BTP045 - Danvanthri Road Junction   0.682238                     2
180    BTP023 - Mahalaxmi Layout Entrance   0.646649                     2
2165         BTP215 - Vanivillas Junction   0.611086                     2
665          BTP067 - Jai Muni Rao Circle   0.610438                     2
1630  BTP163 - 16th Main Road, BTM Layout   0.609273                     2

6 PM Deployment
                               junction_name  city_risk  recommended_officers
849              BTP082 - KR Market Junction   0.836361                     4
2124        BTP211 - Central Street Junction   0.739403                     4
18    BTP001 - 10th Cross, Dr. Rajkumar Road   0.672680                     3
245            BTP027 - Modi Bridge Junction   0.512097                     3
1410              BTP135 - UCO Bank Junction   0.405255                     2
112       BTP016 - 5th Main Road, RPC Layout   0.243925                     1
474        BTP045 - Danvanthri Road Junction   0.213089                     1
1480            BTP140 - Madiwala Check Post   0.209376                     1
932     BTP092 - Bangalore Builders Junction   0.140793                     1
1445   BTP137 - Madiwala Traffic PS Junction   0.109770                     1

In [46]:
print("hourly_risk_final" in globals())
print("behavior_df" in globals())
print("recommend_deployment" in globals())

True
True
True

In [47]:
behavior_df.to_csv(
    "junction_behavior_final.csv",
    index=False
)

hourly_risk_final.to_csv(
    "hourly_risk_final.csv",
    index=False
)

print("Backend files saved.")

Backend files saved.

In [48]:
import os

for f in [
    "junction_behavior_final.csv",
    "hourly_risk_final.csv"
]:
    print(f, "->", os.path.exists(f))

junction_behavior_final.csv -> True
hourly_risk_final.csv -> True

In [49]:
# Rebuild final PDI using named_df

junction_total = (
    named_df.groupby("junction_name")
    .size()
    .rename("total_violations")
)

junction_peak = (
    named_df[named_df["hour_ist"].between(7,10)]
    .groupby("junction_name")
    .size()
    .rename("peak_violations")
)

junction_heavy = (
    named_df[
        named_df["vehicle_type"].isin([
            "HGV",
            "LORRY/GOODS VEHICLE",
            "TANKER",
            "BUS (BMTC/KSRTC)",
            "PRIVATE BUS",
            "TOURIST BUS",
            "SCHOOL VEHICLE"
        ])
    ]
    .groupby("junction_name")
    .size()
    .rename("heavy_violations")
)

active_days = (
    named_df.groupby("junction_name")["date"]
    .nunique()
    .rename("active_days")
)

junction_pdi_final = pd.concat(
    [
        junction_total,
        active_days,
        junction_peak,
        junction_heavy
    ],
    axis=1
).fillna(0)

junction_pdi_final["peak_ratio"] = (
    junction_pdi_final["peak_violations"]
    /
    junction_pdi_final["total_violations"]
)

junction_pdi_final["heavy_ratio"] = (
    junction_pdi_final["heavy_violations"]
    /
    junction_pdi_final["total_violations"]
)

junction_pdi_final["recurrence"] = (
    junction_pdi_final["total_violations"]
    /
    junction_pdi_final["active_days"]
)

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

junction_pdi_final["freq_n"] = scaler.fit_transform(
    junction_pdi_final[["total_violations"]]
)

junction_pdi_final["peak_n"] = scaler.fit_transform(
    junction_pdi_final[["peak_ratio"]]
)

junction_pdi_final["heavy_n"] = scaler.fit_transform(
    junction_pdi_final[["heavy_ratio"]]
)

junction_pdi_final["recur_n"] = scaler.fit_transform(
    junction_pdi_final[["recurrence"]]
)

junction_pdi_final["PDI"] = (
    0.45 * junction_pdi_final["freq_n"] +
    0.25 * junction_pdi_final["peak_n"] +
    0.10 * junction_pdi_final["heavy_n"] +
    0.20 * junction_pdi_final["recur_n"]
) * 100

junction_pdi_final.to_csv(
    "junction_pdi_final.csv"
)

print(junction_pdi_final.shape)

junction_pdi_final.sort_values(
    "PDI",
    ascending=False
).head(20)

(168, 12)

,total_violations,active_days,peak_violations,heavy_violations,peak_ratio,heavy_ratio,recurrence,freq_n,peak_n,heavy_n,recur_n,PDI
junction_name,,,,,,,,,,,,
BTP051 - Safina Plaza Junction,15449,151,8610.0,20.0,0.557318,0.001295,102.311258,1.000000,0.780245,0.002589,1.000000,84.532009
BTP040 - Elite Junction,10718,151,4933.0,47.0,0.460254,0.004385,70.980132,0.693648,0.644355,0.008770,0.690307,61.216871
BTP044 - Sagar Theatre Junction,10549,151,4985.0,146.0,0.472557,0.013840,69.860927,0.682704,0.661579,0.027680,0.679244,61.122860
BTP082 - KR Market Junction,11538,151,3860.0,45.0,0.334547,0.003900,76.410596,0.746746,0.468365,0.007800,0.743985,60.270406
BTP027 - Modi Bridge Junction,4584,148,2228.0,7.0,0.486038,0.001527,30.972973,0.296445,0.680454,0.003054,0.294856,36.279031
BTP211 - Central Street Junction,5388,149,2032.0,20.0,0.377134,0.003712,36.161074,0.348507,0.527988,0.007424,0.346138,35.879533
"BTP080 - NR Road, SP Road Junction",3681,142,1813.0,32.0,0.492529,0.008693,25.922535,0.237972,0.689541,0.017387,0.244935,33.019822
BTP058 - Subbanna Junction,5189,150,1329.0,64.0,0.256119,0.012334,34.593333,0.335621,0.358566,0.024668,0.330642,30.926621
BTP020 - Hosahalli Metro Station,4101,122,1417.0,6.0,0.345525,0.001463,33.614754,0.265169,0.483736,0.002926,0.320969,30.474619
BTP057 - Anand Rao Junction,3935,148,1349.0,234.0,0.342821,0.059466,26.587838,0.254419,0.479949,0.118933,0.251511,29.667155
BTP023 - Mahalaxmi Layout Entrance,1807,139,997.0,119.0,0.551743,0.065855,13.000000,0.116622,0.772441,0.131710,0.117202,28.220162
"BTP178 - 18th Main, Marenahalli",7,4,5.0,1.0,0.714286,0.142857,1.750000,0.000065,1.000000,0.285714,0.006001,27.980083
BTP045 - Danvanthri Road Junction,3181,148,1127.0,166.0,0.354291,0.052185,21.493243,0.205595,0.496008,0.104370,0.201154,26.718722
BTP038 - Mysore Bank Junction,2021,135,1011.0,38.0,0.500247,0.018803,14.970370,0.130480,0.700346,0.037605,0.136678,26.489867
"BTP026 - 1st Block Junction, Rajajinagar",1086,102,650.0,2.0,0.598527,0.001842,10.647059,0.069935,0.837937,0.003683,0.093944,26.011211
"BTP182 - 19th Main Junction, Rajajinagar",1390,121,753.0,1.0,0.541727,0.000719,11.487603,0.089620,0.758417,0.001439,0.102253,25.052770
"BTP102 - BMTC Junction, KH Road",175,73,120.0,2.0,0.685714,0.011429,2.397260,0.010943,0.960000,0.022857,0.012399,24.969011
"BTP001 - 10th Cross, Dr. Rajkumar Road",2812,140,1002.0,5.0,0.356330,0.001778,20.085714,0.181700,0.498862,0.003556,0.187241,24.428449
BTP217 - Baleyele Junction,85,34,55.0,3.0,0.647059,0.035294,2.500000,0.005116,0.905882,0.070588,0.013415,23.851436
BTP075 - Police Corner,188,59,120.0,3.0,0.638298,0.015957,3.186441,0.011785,0.893617,0.031915,0.020200,23.593908

In [51]:
import pandas as pd

behavior = pd.read_csv("junction_behavior_final.csv")
hourly   = pd.read_csv("hourly_risk_final.csv")
pdi      = pd.read_csv("junction_pdi_final.csv")
clusters = pd.read_csv("cluster_hotspots.csv")
stations = pd.read_csv("station_eps.csv")

print("=== BEHAVIOR ===")
print(behavior.columns.tolist())
print(behavior.head(2).to_string())

print("\n=== HOURLY RISK ===")
print(hourly.columns.tolist())
print(hourly.head(2).to_string())

print("\n=== PDI ===")
print(pdi.columns.tolist())
print(pdi.head(2).to_string())

print("\n=== CLUSTERS ===")
print(clusters.columns.tolist())

print("\n=== STATIONS ===")
print(stations.columns.tolist())

=== BEHAVIOR ===
['junction_name', 'daily_avg', 'daily_std', 'daily_max', 'active_days', 'consistency', 'spike_ratio', 'growth_rate', 'hotspot_type', 'priority_level']
                            junction_name  daily_avg  daily_std  daily_max  active_days  consistency  spike_ratio  growth_rate hotspot_type priority_level
0  BTP001 - 10th Cross, Dr. Rajkumar Road  20.085714  17.579618         84          140     0.124770     4.182077    -0.302832       STABLE           HIGH
1          BTP006 - Navarang Bar Junction   3.357143   2.924884          9           14     0.128758     2.680851    -0.210526       STABLE            LOW

=== HOURLY RISK ===
['junction_name', 'hour_ist', 'violations', 'risk_score', 'total_violations', 'volume_score', 'city_risk']
                            junction_name  hour_ist  violations  risk_score  total_violations  volume_score  city_risk
0  BTP001 - 10th Cross, Dr. Rajkumar Road         0    2.250000    0.204545              2812        0.1817   0.195407
1  BTP001 - 10th Cross, Dr. Rajkumar Road         1    3.714286    0.337662              2812        0.1817   0.275278

=== PDI ===
['junction_name', 'total_violations', 'active_days', 'peak_violations', 'heavy_violations', 'peak_ratio', 'heavy_ratio', 'recurrence', 'freq_n', 'peak_n', 'heavy_n', 'recur_n', 'PDI']
                            junction_name  total_violations  active_days  peak_violations  heavy_violations  peak_ratio  heavy_ratio  recurrence    freq_n    peak_n   heavy_n   recur_n        PDI
0  BTP001 - 10th Cross, Dr. Rajkumar Road              2812          140           1002.0               5.0    0.356330     0.001778   20.085714  0.181700  0.498862  0.003556  0.187241  24.428449
1          BTP006 - Navarang Bar Junction                47           14             16.0               1.0    0.340426     0.021277    3.357143  0.002655  0.476596  0.042553  0.021887  12.897640

=== CLUSTERS ===
['cluster', 'violations', 'peak_violations', 'heavy_violations', 'center_lat', 'center_lon', 'active_days', 'PDI']

=== STATIONS ===
['police_station', 'total_violations', 'avg_pdi', 'peak_violations', 'heavy_violations', 'EPS']